asterisk/asterisk

- main/say.c
ast_waitstream was not called after ast_streamfile, resulting in "o'clock" being skipped in French.
Additionally, the minute announcements should be feminine.
Reported-by: Danny Lloyd
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/20035
Resolves: #41
ASTERISK-30488
> say.c: Fix French time playback.

- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip/security_agreements.c
- res/res_pjsip_outbound_registration.c
- res/res_pjsip_rfc3329.c
When using mediasec, requests sent after a 401 must still contain the
Security-Client header according to
draft-dawes-sipcore-mediasec-parameter.
Resolves: #48
> res_pjsip: mediasec: Add Security-Client headers after 401

- include/asterisk/cel.h
- main/cel.c
The current AST_CEL_LOCAL_OPTIMIZE event is and has been
triggered on a local optimization end to serve as a flag
indicating the event occurred. This change adds a second
AST_CEL_LOCAL_OPTIMIZE_BEGIN event for further detail.
Resolves: https://github.com/asterisk/asterisk/issues/52
UpgradeNote: The existing AST_CEL_LOCAL_OPTIMIZE can continue
to be used as-is and the AST_CEL_LOCAL_OPTIMIZE_BEGIN event
can be ignored if desired.
UserNote: The new AST_CEL_LOCAL_OPTIMIZE_BEGIN can be used
by itself or in concert with the existing
AST_CEL_LOCAL_OPTIMIZE to book-end local channel optimization.
> cel: add local optimization begin event

- res/res_pjsip_session.c
We should also return all codecs on an re-INVITE without SDP for a call that used late offer (e.g. no SDP in the initial INVITE, SDP in the ACK). Bugfix for feature introduced in ASTERISK-30193 (https://issues.asterisk.org/jira/browse/ASTERISK-30193)
Migration from previous gerrit change that was not merged.
> chan_pjsip: also return all codecs on empty re-INVITE for late offers

- include/asterisk/utils.h
Deprecate `ast_gethostbyname()` in favor of `ast_sockaddr_resolve()` and `ast_sockaddr_resolve_first_af()`. `ast_gethostbyname()` has not been used by any in-tree code since 2021.
This function will be removed entirely in Asterisk 23.
Resolves: #78
UpgradeNote: ast_gethostbyname() has been deprecated and will be removed in Asterisk 23. New code should use `ast_sockaddr_resolve()` and `ast_sockaddr_resolve_first_af()`.
> utils.h: Deprecate `ast_gethostbyname()`.

- res/res_sorcery_memory_cache.c
The pointer returned by ast_strdup had never been freed.
Resolves: https://github.com/asterisk/asterisk/issues/55
[ASTERISK-30429](https://issues.asterisk.org/jira/browse/ASTERISK-30429)
> res_sorcery_memory_cache.c: Fix memory leak.

- configure
- configure.ac
- include/asterisk/autoconfig.h.in
- res/res_pjsip_pubsub.c
- third-party/pjproject/configure.m4
The functionality we are interested in is present only in pjsip 2.13 and newer.
Resolves: #45
> res_pjsip_pubsub.c: Use pjsip version for pending NOTIFY check.

- include/asterisk/res_pjsip_pubsub.h
- res/res_pjsip_pubsub.c
The existing res_pjsip_pubsub APIs are somewhat limited in what they can do. This adds a few API extensions that make it possible for PJSIP pubsub modules to implement richer features than is currently possible.
* Allow pubsub modules to get a handle to pjsip_rx_data on subscription
* Allow pubsub modules to run a callback when a subscription is renewed
* Allow pubsub modules to run a callback for outgoing NOTIFYs, with a handle to the tdata, so that modules can append their own headers to the NOTIFYs
This change does not add any features directly, but makes possible several new features that will be added in future changes.
Resolves: #81
ASTERISK-30485 #close
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/20031
Master-Only: True
> res_pjsip_pubsub: Add new pubsub module capabilities.

- doc/asterisk.8
- main/asterisk.c
Commit 09e989f972e2583df4e9bf585c246c37322d8d2f
categorized the T option as not being compatible
with remote consoles, but they do affect verbose
messages with remote console. This fixes this.
Resolves: #102
> asterisk.c: Fix option warning for remote console.

- channels/chan_dahdi.c
- channels/sig_analog.c
The hidecallerid setting in chan_dahdi.conf currently is broken for a couple reasons.
First, the actual code in sig_analog to "allow" or "block" Caller ID depending on this setting improperly used ast_set_callerid instead of updating the presentation. This issue was mostly fixed in ASTERISK_29991, and that fix is carried forward to this code as well.
Secondly, the hidecallerid setting is set on the DAHDI pvt but not carried forward to the analog pvt properly. This is because the chan_dahdi config loading code improperly set permhidecallerid to permhidecallerid from the config file, even though hidecallerid is what is actually set from the config file. (This is done correctly for call waiting, a few lines above.) This is fixed to read the proper value.
Thirdly, in sig_analog, hidecallerid …
> chan_dahdi: Fix broken hidecallerid setting.

- contrib/scripts/asterisk.logrotate
The Asterisk logrotate script contains explicit
references to files with the .log extension,
which are also included when *log is expanded.
This causes issues with newer versions of logrotate. This fixes this by ensuring that a log file cannot be referenced multiple times after expansion occurs.
Resolves: #96
ASTERISK-30442
Reported by: EN Barnett
Tested by: EN Barnett
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/19929
> logrotate: Fix duplicate log entries.

- include/asterisk/callerid.h
- main/callerid.c
The Caller ID generation routine currently is hardcoded to always use the system time zone. This makes it possible to optionally specify any TZ-format time zone.
Resolves: #98
ASTERISK-30330
Imported from: https://gerrit.asterisk.org/c/asterisk/+/19600
> callerid: Allow specifying timezone for date/time.

- apps/app_queue.c
- contrib/ast-db-manage/config/versions/4042a0ff4d9f_add_reason_paused_to_queue_members.py
When Asterisk is restarted it does not preserve paused reason for
members of realtime queues. This was fixed for non-realtime queues in
ASTERISK_25732
Resolves: #66
UpgradeNote: Add a new column to the queue_member table:
reason_paused VARCHAR(80) so the reason can be preserved.
UserNote: Make paused reason in realtime queues persist an
Asterisk restart. This was fixed for non-realtime
queues in ASTERISK_25732.
> apps/app_queue: Preserve reason for realtime queues

- channels/chan_dahdi.c
- channels/sig_analog.c
- channels/sig_analog.h
- configs/samples/chan_dahdi.conf.sample
- funcs/func_callerid.c
A previous change, ASTERISK_29991, made it possible to send additional Caller ID parameters that were
not previously supported.
This change adds support for analog DAHDI channels to now be able to receive these parameters for
on-hook Caller ID, in order to enhance the usability of CPE that support these parameters.
Resolves: #94
ASTERISK-30331
UserNote: Additional Caller ID properties are now supported on incoming calls to FXS stations, namely the
redirecting reason and call qualifier.
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/19601
> sig_analog: Add fuller Caller ID support.

- channels/chan_dahdi.c
Currently, the presentation for incoming channels is always available, because it is never actually set, meaning the channel presentation can be nonsensical. If the presentation from the incoming Caller ID spill is private or unavailable, we now update the channel presentation to reflect this.
Resolves: #120
ASTERISK-30333
ASTERISK-21741
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/19603
> chan_dahdi: Fix Caller ID presentation for FXO ports.

- configure
- configure.ac
Makefile downloader enable follow redirects.
If curl is used for building, any download such as a sounds package
will fail to follow HTTP redirects and will download wrong data.
Resolves: #136
> configure: Makefile downloader enable follow redirects.

- include/asterisk/app.h
- main/loader.c
- main/stasis_message.c
- tests/test_utils.c
* gcc 13 is now catching when a function is declared as returning
an enum but defined as returning an int or vice versa.  Fixed
a few in app.h, loader.c, stasis_message.c.
* gcc 13 is also now (incorrectly) complaining of dangling pointers
when assigning a pointer to a local char array to a char *. Had
to change that to an ast_alloca.
Resolves: #155
> build: Fix a few gcc 13 issues

- res/parking/parking_manager.c
Add a parking space extension parameter (ParkingSpace) to the Park action.
Park action will attempt to park the call to that extension.
If the extension is already in use, then execution will continue at the next priority.
> AMI: Add parking position parameter to Park action

- main/tcptls.c
If we don't set this to -1 if the structure can be potentially re-used later then it's possible that we'll issue a close() on an unrelated file descriptor, breaking asterisk in other interesting ways.
I believe this to be an unlikely scenario, but it costs nothing to be safe.
> tcptls: when disabling a server port, we should set the accept_fd to -1.

- res/res_fax_spandsp.c
Clean up a spaces/tabs issue in res_fax_spandsp.c
> res_fax_spandsp.c: Clean up a spaces/tabs issue

- autoconf/ax_pthread.m4
- configure
- configure.ac
- include/asterisk/autoconfig.h.in
- menuselect/configure.ac
These were uncovered when trying to run `bootstrap.sh` with Autoconf
2.71:
* AC_CONFIG_HEADER() is deprecated in favor of AC_CONFIG_HEADERS().
* AC_HEADER_TIME is obsolete.
* $as_echo is deprecated in favor of AS_ECHO() which requires an update
to ax_pthread.m4.
Note that the generated artifacts in this commit are from Autoconf 2.69.
Resolves https://github.com/asterisk/asterisk/issues/139
> configure: Remove obsolete and deprecated constructs.

- apps/app_queue.c
- configs/samples/queues.conf.sample
This adds an option 'force_longest_waiting_caller' which changes the
global behavior of the queue engine to prevent queue callers from
'jumping ahead' when an agent is in multiple queues.
Previously reviewed here: https://gerrit.asterisk.org/c/asterisk/+/19793
Resolves: #108
Also closes old asterisk issues:
- ASTERISK-17732
- ASTERISK-17570
Change-Id: I0f84e27903fefbe2018d0afa2d67b23aa0b321ce
> app_queue: Add force_longest_waiting_caller option.

- include/asterisk/res_pjsip_session.h
- res/res_pjsip_session.c
Added two new functions (ast_sip_session_get_dialog and
ast_sip_session_get_pjsip_inv_state) that retrieve the dialog and the
pjsip_inv_state respectively from the pjsip_inv_session on the
ast_sip_session struct. This is due to pjproject adding a new field to
the pjsip_inv_session struct that caused crashes when trying to access
fields that were no longer where they were expected to be if a module
was compiled against a different version of pjproject.
Resolves: #145
> res_pjsip_session: Added new function calls to avoid ABI issues.

- Makefile
- rest-api-templates/api.wiki.mustache
- rest-api-templates/make_ari_stubs.py
- rest-api-templates/models.wiki.mustache
- rest-api-templates/swagger_model.py
The new documentation site uses traditional markdown instead
of the Confluence flavored version.  This required changes in
the mustache templates and the python that generates the files.
> rest-api: Updates for new documentation site

- res/res_musiconhold.c
Move channel unlock to after moh state access to avoid
potential unlocked access to state.
Resolves: #133
> res_musiconhold: avoid moh state access on unlocked chan

- apps/app_voicemail.c
Fixes two compilation errors in app_voicemail_imap, one due to an unsed
variable and one due to a new variable added in the incorrect location
in _163.
Resolves: #174
> app_voicemail: fix imap compilation errors

- third-party/pjproject/patches/0250-Fix-double-free-of-ossock-ossl_ctx-in-case-of-errors.patch
- third-party/pjproject/patches/0251-free-SSL-context-and-reset-context-pointer-when-sett.patch
* Fix double free of ossock->ossl_ctx in case of errors
https://github.com/pjsip/pjproject/commit/863629bc65d6
* free SSL context and reset context pointer when setting the cipher
list fails
https://github.com/pjsip/pjproject/commit/0fb32cd4c0b2
Resolves: #194
> bundled_pjproject: Backport 2 SSL patches from upstream

- channels/chan_dahdi.c
- channels/chan_dahdi.h
- channels/sig_analog.c
- channels/sig_analog.h
- configs/samples/chan_dahdi.conf.sample
When immediate=yes on an FXS channel, sig_analog will start fake audible ringback that continues until the channel is answered. Even if it answers immediately, the ringback is still audible for a brief moment.
This can be disruptive and unwanted behavior.
This adds an option to disable this behavior, though the default behavior remains unchanged.
Resolves: #118
ASTERISK-30003
Imported from: https://gerrit.asterisk.org/c/asterisk/+/19715
UserNote: The immediatering option can now be set to no to suppress the fake audible ringback provided
when immediate=yes on FXS channels.
> sig_analog: Allow immediate fake ring to be suppressed.

- configs/samples/users.conf.sample
- pbx/pbx_config.c
This deprecates the users.conf config file, which
is no longer as widely supported but still integrated with a number of different modules.
Because there is no real mechanism for marking a
configuration file as "deprecated", and users.conf is not just used in a single place, this now emits a warning to the user when the PBX loads to notify about the deprecation.
This configuration mechanism has been widely criticized and discouraged since its inception, and is no longer relevant to the configuration that most users are doing today. Removing it will allow for some simplification and cleanup in the codebase.
Resolves: #183
UpgradeNote: The users.conf config is now deprecated and will be removed in a future version of Asterisk.
> users.conf: Deprecate users.conf configuration.

- res/res_rtp_asterisk.c
res_rtp_asterisk: Move ast_rtp_rtcp_report_alloc using `rtp->themssrc_valid` into the scope of the rtp_instance lock.
From the gdb information, it was found that when calling __ast_free, the size of the
allocated space pointed to by the pointer matches the size created when rtp->themssrc_valid
is equal to 0. However, in reality, when reading the value of rtp->themssrc_valid in gdb,
it is found to be 1.
Within ast_rtcp_write(), the call to ast_rtp_rtcp_report_alloc() uses rtp->themssrc_valid,
which is outside the protection of the rtp_instance lock. However,
ast_rtcp_generate_report(), which is called by ast_rtcp_generate_compound_prefix(), uses
rtp->themssrc_valid within the protection of the rtp_instance lock.
This can lead to the possibility that the value of rtp->themssrc_valid used in …
> res_rtp_asterisk: Move ast_rtp_rtcp_report_alloc using `rtp->themssrc_valid` into the scope of the rtp_instance lock.

- apps/app_voicemail.c
Adds CLI commands to allow move/remove/forward individual messages
from a particular mailbox folder. The forward command can be used
to copy a message within a mailbox or to another mailbox. Also adds
a show mailbox, required to retrieve message ID's.
Resolves: #170
UserNote: The following CLI commands have been added to app_voicemail
voicemail show mailbox \<mailbox> \<context>
Show contents of mailbox \<mailbox>\@\<context>
voicemail remove \<mailbox> \<context> \<from_folder> \<messageid>
Remove message \<messageid> from \<from_folder> in mailbox \<mailbox> \@ \<context>
voicemail move \<mailbox> \<context> \<from_folder> \<messageid> \<to_folder>
Move message \<messageid> in mailbox \<mailbox> \@ \<context> from \<from_folder> to \<to_folder>
voicemail forward \<from_mailbox> …
> app_voicemail: add CLI commands for message manipulation

- apps/app_voicemail.c
Adds manager actions to allow move/remove/forward individual messages in a particular mailbox folder. The forward command can be used to copy a message within a mailbox or to another mailbox. Also adds a VoicemailBoxSummarry, required to retrieve message ID's.
Resolves: #181
UserNote: The following manager actions have been added
VoicemailBoxSummary - Generate message list for a given mailbox
VoicemailRemove - Remove a message from a mailbox folder
VoicemailMove - Move a message from one folder to another within a mailbox
VoicemailForward - Copy a message from one folder in one mailbox
to another folder in another or the same mailbox.
> app_voicemail - add manager actions to display and manipulate messages

- channels/chan_iax2.c
A change made in 82cebaa0 did not properly handle the case when a channel was not provided, triggering a crash. ast_check_hangup(...) does not protect against NULL pointers.
Fixes #180
> chan_iax2.c: Avoid crash with IAX2 switch support.

- include/asterisk/app.h
The ast_app_getdata() and ast_app_getdata_terminator() declarations
in app.h were changed recently to return enum ast_getdata_result
(which is how they were defined in app.c).  The existing
declaration of ast_getdata_result in app.h was about 1000 lines
after those functions however so under certain circumstances,
a "use before declaration" error was thrown by the compiler.
The declaration of the enum was therefore moved to before those
functions.
Resolves: #200
> app.h: Move declaration of ast_getdata_result before its first use

- funcs/func_export.c
> func_export: Use correct function argument as variable name.

- configs/samples/extensions.ael.sample
- configs/samples/extensions.conf.sample
- configs/samples/extensions.lua.sample
- configs/samples/iax.conf.sample
c3ff4648 removed the `[iaxtel700]` context but neglected to remove references to it.
This commit addresses that and also removes iaxtel and freeworlddialup references from other config files.
> extensions.conf.sample: Remove reference to missing context.

- funcs/func_cut.c
This adds an example to the XML documentation clarifying usage of the 
CUT function to address a common misusage.
> func_cut: Add example to documentation.

- res/prometheus/bridges.c
- tests/test_res_prometheus.c
In 8d6fdf9c3adede201f0ef026dab201b3a37b26b6 invisible bridges were skipped but that lead to producing metrics with no name and no help.
Keep track of the number of metrics configured and then only emit these. Add a basic testcase that verifies that there is no '(NULL)' in the output.
ASTERISK-30474
> res_prometheus: Do not generate broken metrics

- channels/chan_dahdi.c
- channels/chan_dahdi.h
- channels/sig_analog.c
- channels/sig_analog.h
- configs/samples/chan_dahdi.conf.sample
sig_analog allows users to flash and use the three-way dial tone as a primitive hold function, simply by never timing it out.
Some systems allow this dial tone to time out to silence, so the user is not annoyed by a persistent dial tone. This option allows the dial tone to time out normally to silence.
Resolves: #205
ASTERISK-30004 #close
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/19716
UserNote: The threewaysilenthold option now allows the three-way dial tone to time out to silence, rather than continuing forever.
> sig_analog: Allow three-way flash to time out to silence.

- channels/chan_dahdi.c
- channels/chan_dahdi.h
- configs/samples/chan_dahdi.conf.sample
Currently, if an FXS channel is still off hook when all calls on the line have hung up, the user is provided reorder tone until going back on hook again.
In addition to not reflecting what most commercial switches actually do, it's very common for switches to automatically reoriginate for the user so that dial tone is provided without the user having to depress and release the hookswitch manually. This can increase convenience for users.
This behavior is now supported for kewlstart FXS channels. It's supported only for kewlstart (FXOKS) mainly because the behavior doesn't make any sense for ground start channels, and loop start signalling doesn't provide the necessary DAHDI event that makes this easy to implement. Likely almost everyone is using FXOKS over FXOLS anyways since FXOLS is …
> chan_dahdi: Allow autoreoriginating after hangup.

- main/manager_channels.c
In some cases I have yet to determine some stasis messages may be created without a channel snapshot. This change adds some tolerance to this scenario, preventing a crash from occurring.
> manager: Tolerate stasis messages with no channel snapshot.

- third-party/pjproject/patches/config_site.h
The default is 32 with 8 being used by pjproject itself.  Recent
commits have put us over the limit resulting in assertions in
pjproject.  Since this value is used in invites, dialogs,
transports and subscriptions as well as the global pjproject
endpoint, we don't want to increase it too much.
Resolves: #255
> pjproject_bundled: Increase PJSIP_MAX_MODULE to 38

- res/res_pjsip_header_funcs.c
The documentation for PJSIP_HEADERS claims that
prefix is optional, but in the code it is actually not. However, there is no inherent reason for this, as users may want to retrieve all header names, not just those beginning with a certain prefix.
This makes the prefix optional for this function,
simply fetching all header names if not specified. As a result, the documentation is now correct.
Resolves: #230
UserNote: The prefix argument to PJSIP_HEADERS is now optional. If not specified, all header names will be returned.
> res_pjsip_header_funcs: Make prefix argument optional.

- res/ari/resource_endpoints.h
An earlier cherry-pick that involved rest-api somehow didn't include
a comment change in res/ari/resource_endpoints.h.  This commit
corrects that.  No changes other than the comment.
Was already fixed in master.
> rest-api: Run make ari-stubs

- configs/samples/res_config_odbc.conf.sample
- configs/samples/res_pgsql.conf.sample
- res/res_config_odbc.c
- res/res_config_pgsql.c
Added a new boolean configuration flag - `order_multi_row_results_by_initial_column` - to both res_pgsql.conf and res_config_odbc.conf that allows the administrator to disable the explicit `ORDER BY` that was previously being added to all generated SQL statements that returned multiple rows.
Fixes: #179
> extconfig: Allow explicit DB result set ordering to be disabled.

- res/res_pjsip.c
If the contact_user in declared in the endpoint, the contact_user will be inserted in the message for the incoming calls which it was not the case before. The contact_user is already used in the outgoing calls. 
Resolves: #226
> res_pjsip.c: Add the contact_user to the Contact header

- contrib/scripts/install_prereq
Fixes dependency solutions in `install_preqreq` for Debian aarch64 platforms. `install_prereq` was attempting to forcibly install 32-bit armhf packages due to the aptitude search for dependencies.
Resolves: #37
> install_prereq:	Fix dependency install on aarch64.

- apps/app_macro.c
app_macro sometimes would crash due to datastore list corruption on the
channel because of lack of locking around find and create process for
the macro datastore. This patch locks the channel lock prior to protect
against this problem.
Resolves: #265
> app_macro: Fix locking around datastore access

- build_tools/download_externals
* Fixed issue with the script not parsing the new tag format for
certified releases.  The format changed from certified/18.9-cert5
to certified-18.9-cert5.
* Fixed issue where the asterisk version wasn't being considered
when looking for cached versions.
Resolves: #263
> download_externals:  Fix a few version related issues

- funcs/func_global.c
- funcs/func_logic.c
Using the Set dialplan application does not actually
delete channel or global variables. Instead the
variables are set to an empty value.
This change adds two dialplan functions,
GLOBAL_DELETE and DELETE which can be used to
delete global and channel variables instead
of just setting them to empty.
There is also no ability within the dialplan to
determine if a global or channel variable has
actually been set or not.
This change also adds two dialplan functions,
GLOBAL_EXISTS and VARIABLE_EXISTS which can be
used to determine if a global or channel variable
has been set or not.
Resolves: #289
UserNote: Four new dialplan functions have been added.
GLOBAL_DELETE and DELETE have been added which allows
the deletion of global and channel variables.
GLOBAL_EXISTS and VARIABLE_EXISTS have been …
> variables: Add additional variable dialplan functions.

- contrib/scripts/safe_asterisk
If the safe_asterisk script detects that the /var/lib/asterisk
directory doesn't exist, it now creates it with 755 permissions
instead of 770.  safe_asterisk needing to create that directory
should be extremely rare though because it's normally created
by 'make install' which already sets the permissions to 755.
Resolves: #316
> safe_asterisk: Change directory permissions to 755

- res/res_speech_aeap.c
* Fixed issue in res_speech_aeap when unable to provide an
input format to check against.
> res_speech_aeap: check for null format on response

- funcs/func_periodic_hook.c
func_periodic_hook does not hangup after playback, relying on timeout
which keeps the channel alive longer than necessary.
Resolves: #325
> func_periodic_hook: Add hangup step to avoid timeout

- Makefile
- build_tools/cflags.xml
- build_tools/make_buildopts_h
- build_tools/make_version_c
- include/asterisk/ast_version.h
- main/asterisk.c
The previous behavior of make_buildopts_h was to not add the
non-ABI-breaking MENUSELECT_CFLAGS like DETECT_DEADLOCKS,
REF_DEBUG, etc. to the buildopts.h file because "it caused
ccache to invalidate files and extended compile times". They're
only defined by passing them on the gcc command line with '-D'
options.   In practice, including them in the include file rarely
causes any impact because the only time ccache cares is if you
actually change an option so the hit occurrs only once after
you change it.
OK so why would we want to include them?  Many IDEs follow the
include files to resolve defines and if the options aren't in an
include file, it can cause the IDE to mark blocks of "ifdeffed"
code as unused when they're really not.
So...
* Added a new menuselect compile option …
> make_buildopts_h, et. al.  Allow adding all cflags to buildopts.h

- res/res_rtp_asterisk.c
In function  rtp_ioqueue_thread_remove counter in ioqueue object is not decreased
which prevents unused ICE TURN threads from being removed.
Resolves: #301
> res_rtp_asterisk: fix wrong counter management in ioqueue objects

- configs/samples/asterisk.conf.sample
- include/asterisk/options.h
- main/asterisk.c
- main/file.c
- main/manager.c
- main/options.c
To better co-exist with sounds files that may be managed by
packages, custom sound files may now be placed in
AST_DATA_DIR/sounds/custom instead of the standard
AST_DATA_DIR/sounds/<lang> directory.  If the new
"sounds_search_custom_dir" option in asterisk.conf is set
to "true", asterisk will search the custom directory for sounds
files before searching the standard directory.  For performance
reasons, the "sounds_search_custom_dir" defaults to "false".
Resolves: #315
UserNote: A new option "sounds_search_custom_dir" has been added to
asterisk.conf that allows asterisk to search
AST_DATA_DIR/sounds/custom for sounds files before searching the
standard AST_DATA_DIR/sounds/<lang> directory.
> file.c: Add ability to search custom dir for sounds

- channels/chan_console.c
To terminate a console channel, stop_stream causes pthread_cancel to make stream_monitor exit. However, commit 5b8fea93d106332bc0faa4b7fa8a6ea71e546cac added locking to this function which results in deadlock due to the stream_monitor thread being killed while it's holding the pvt lock.
To resolve this, a flag is now set and read to indicate abort, so the use of pthread_cancel and pthread_kill can be avoided altogether.
Resolves: #308
> chan_console: Fix deadlock caused by unclean thread exit.

- include/asterisk/cel.h
- main/cel.c
Add a wrapper function around ast_cel_publish_event that
packs event and extras into a blob before publishing
Resolves:#330
> cel: add publish user event helper

- main/asterisk.c
The CLI .asterisk_history file is read from/written to the directory
specified by the HOME environment variable. If the root user starts
asterisk with the -U/-G options, or with runuser/rungroup set in
asterisk.conf, the asterisk process is started as root but then it
calls setuid/setgid to set the new user/group. This does NOT reset
the HOME environment variable to the new user's home directory
though so it's still left as "/root". In this case, the new user
will almost certainly NOT have access to read from or write to the
history file.
* Added function process_histfile() which calls
getpwuid(geteuid()) and uses pw->dir as the home directory
instead of the HOME environment variable.
* ast_el_read_default_histfile() and ast_el_write_default_histfile()
have been modified to use the new …
> asterisk.c: Use the euid's home directory to read/write cli history

- build_tools/cflags-devmode.xml
- include/asterisk/lock.h
- main/lock.c
Previously, DETECT_DEADLOCKS depended on DEBUG_THREADS.
Unfortunately, DEBUG_THREADS adds a lot of lock tracking overhead
to all of the lock lifecycle calls whereas DETECT_DEADLOCKS just
causes the lock calls to loop over trylock in 200us intervals until
the lock is obtained and spits out log messages if it takes more
than 5 seconds.  From a code perspective, the only reason they were
tied together was for logging.  So... The ifdefs in lock.c were
refactored to allow DETECT_DEADLOCKS to be enabled without
also enabling DEBUG_THREADS.
Resolves: #321
> lock.c: Separate DETECT_DEADLOCKS from DEBUG_THREADS

- apps/app_voicemail.c
If ADSI is available on a channel, app_voicemail will repeatedly try to use ADSI, even if there is no CPE that supports it. This leads to many unnecessary delays during the session. If ADSI is available but ADSI setup fails, we now disable it to prevent further attempts to use ADSI during the session.
Resolves: #354
> app_voicemail: Disable ADSI if unavailable.

- funcs/func_json.c
- include/asterisk/json.h
- main/json.c
This commit fixes crashes in JSON_DECODE() for types null, true, false and real numbers.
In addition it ensures that a path is not deeper than 32 levels.
Also allow root object to be an array.
Add unit tests for above cases.
> func_json: Fix crashes for some types

- channels/chan_dahdi.c
- configs/samples/chan_dahdi.conf.sample
Internally, chan_dahdi only applies callgroup and
pickupgroup to FXO signalled channels, but this is not documented anywhere. This is now documented in the sample config, and a warning is emitted if a
user tries configuring these settings for channel
types that do not support these settings, since they will not have any effect.
Resolves: #294
> chan_dahdi: Clarify scope of callgroup/pickupgroup.

- res/res_pjsip/pjsip_config.xml
The documentation on qualify_timeout does not explicitly state that the timeout
includes any time required to perform any needed DNS queries on the endpoint.
If the OPTIONS response is delayed due to the DNS query, it can still render an
endpoint as Unreachable if the net time is enough for qualify_timeout to expire.
Resolves: #352
> res_pjsip: update qualify_timeout documentation with DNS note

- include/asterisk/logger.h
You can now define the _TRACE_PREFIX_ macro to change the
default trace line prefix of "file:line function" to
something else.  Full documentation in logger.h.
> logger.h: Add ability to change the prefix on SCOPE_TRACE output

- res/ari/resource_bridges.c
Make it possible to start a playback and the calling party to receive audio on a bridge before the call is connected.
Model the implementation after play_on_channel and deliver a AST_CONTROL_PROGRESS before starting the playback.
For a pjsip channel this will result in sending a SIP 183 Session Progress.
> ari/stasis: Indicate progress before playback on a bridge

- res/res_stasis.c
- res/stasis/control.c
- res/stasis/control.h
res_statsis's app loop sleeps for up to .2s waiting on input
to a channel before re-checking the command queue. This can
cause delays between channel setup and bridge.
This change is to send a SIGURG on the sleeping thread when
a new command is enqueued. This exits the sleeping thread out
of the ast_waitfor() call triggering the new command being
processed on the channel immediately.
Resolves: #362
UserNote: Call setup times should be significantly improved
when using ARI.
> res_stasis: signal when new command is queued

- contrib/ast-db-manage/config/versions/dac2b4c328b8_incease_pjsip_id_length.py
- include/asterisk/res_pjsip.h
- res/ari/internal.h
- res/res_pjsip/pjsip_distributor.c
- res/res_pjsip_authenticator_digest.c
- res/res_pjsip_endpoint_identifier_user.c
res_pjsip: Expanding pj_sip endpoint ID and relevant resource length to 255 characters
This commit introduces an extension to the endpoint and relevant resource sizes for pj_sip, transitioning from its current 40-character constraint to a more versatile 255-character capacity. This enhancement significantly overcomes limitations related to domain qualification and practical usage, ultimately delivering improved functionality. Furthermore, it encompasses adjustments to the realtime database schema and ARI message length to seamlessly accommodate the expanded realm size.
Resolves: #345
> res_pjsip: Expanding PJSIP endpoint ID and relevant resource length to 255 characters

- res/res_pjsip_exten_state.c
- res/res_pjsip_mwi.c
Commit f66f77f last year prevents the res_pjsip_exten_state and
res_pjsip_mwi modules from unloading due to possible pjproject
asserts if the modules are reloaded. A side effect of the
implementation is that the taskprocessors these modules use aren't
being released. When asterisk is doing a graceful shutdown, it
waits AST_TASKPROCESSOR_SHUTDOWN_MAX_WAIT seconds for all
taskprocessors to stop but since those 2 modules don't release
theirs, the shutdown hangs for that amount of time.
This change allows the modules to be unloaded and their resources to
be released when ast_shutdown_final is true.
Resolves: #379
> res_pjsip_exten_state,res_pjsip_mwi: Allow unload on shutdown

- configs/samples/pjsip.conf.sample
> configs: Fix typo in pjsip.conf.sample.

- res/res_pjsip/pjsip_configuration.c
Per RFC8827:
Implementations MUST NOT implement DTLS renegotiation and MUST
reject it with a "no_renegotiation" alert if offered.
So we disable it when webrtc=yes is set.
Fixes #378
UpgradeNote: The dtls_rekey will be disabled if webrtc support is requested on an endpoint. A warning will also be emitted.
> pjsip_configuration.c: Disable DTLS renegotiation if WebRTC is enabled.

- rest-api-templates/api.wiki.mustache
The '*' list indicator for default values and allowable values for
path, query and POST parameters need to be indented 4 spaces
instead of 2.
Should resolve issue 38 in the documentation repo.
> api.wiki.mustache: Fix indentation in generated markdown

- res/res_pjsip_dtmf_info.c
> res_pjsip_dtmf_info.c: Add 'INFO' to Allow header.

- res/res_rtp_asterisk.c
> res_rtp_asterisk.c: Fix memory leak in ephemeral certificate creation.

- res/res_speech.c
* Allow res_speech to translate the input channel if the
format is translatable to a format supported by the
speech provider.
Resolves: #129
UserNote: res_speech now supports translation of an input channel
to a format supported by the speech provider, provided a translation
path is available between the source format and provider capabilities.
> res_speech: allow speech to translate input channel

- bridges/bridge_simple.c
In simple_bridge_join, we were sending topology change requests
even when the new and old topologies were the same.  In some
circumstances, this can cause unnecessary re-invites and even
a re-invite flood.  We now suppress those.
Resolves: #384
> bridge_simple: Suppress unchanged topology change requests

- main/core_local.c
Currently, trying to call a Local channel with a slash in the extension will fail due to the parsing of characters after such a slash as being dial modifiers. Additionally, core_local is inconsistent and incomplete with
its parsing of Local dial strings in that sometimes it uses the first slash and at other times it uses the last.
For instance, something like DAHDI/5 or PJSIP/device is a perfectly usable extension in the dialplan, but Local channels in particular prevent these from being called.
This creates inconsistent behavior for users, since using a slash in an extension is perfectly acceptable, and using a Goto to accomplish this works fine, but if specified through a Local channel, the parsing prevents this.
This fixes this by explicitly parsing options from the last slash in the …
> core_local: Fix local channel parsing with slashes.

- res/res_rtp_asterisk.c
The module will fail to load. Use proper function DTLS_method() with LibreSSL.
> res_rtp_asterisk.c: Fix runtime issue with LibreSSL

- main/utils.c
Implement the ast_get_tid() function for OpenBSD. OpenBSD supports
getting the TID via getthrid().
> main/utils: Implement ast_get_tid() for OpenBSD

- main/channel.c
- main/stasis_channels.c
- res/ari/ari_model_validators.c
- res/ari/ari_model_validators.h
- rest-api/api-docs/channels.json
- tests/test_stasis_channels.c
Add the `caller_rdnis` attribute to the channel in ARI. Update the channel snapshot before publishing the hangup request to have the latest information.
> ARI/stasis: Indicate the diversion target and make it available in hangup request

- channels/chan_dahdi.c
If attempting to ring a channel using a nonexistent cadence, emit a warning, before falling back to the default cadence.
Resolves: #409
> chan_dahdi: Warn if nonexistent cadence is requested.

- channels/iax2/parser.c
When IAX2 debugging was enabled (`iax2 set debug on`), if the last IE in a frame was one that may not have any data - such as the CALLTOKEN IE in an NEW request - it was not getting displayed.
> chan_iax2.c: Ensure all IEs are displayed when dumping frame contents.

- configure
- configure.ac
Fedora 37 started shipping ilbc 3.0.4 which we don't yet support.
configure.ac now checks the system for "libilbc < 3" instead of
just "libilbc".  If true, the system version of ilbc will be used.
If not, the version included at codecs/ilbc will be used.
Resolves: #84
> codec_ilbc: Disable system ilbc if version >= 3.0.0

- channels/iax2/parser.c
This resolves an issue where non-printable characters could be sent to the console/log files.
> chan_iax2.c: Don't send unsanitized data to the logger.

- main/logger.c
This adds the ability to filter console
logging by channel or groups of channels.
This can be useful on busy systems where
an administrator would like to analyze certain
calls in detail. A dialplan application is also
included for the purpose of assigning a channel
to a group (e.g. by tenant, or some other metric).
ASTERISK-30483 #close
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/20029
Resolves: #242
UserNote: The console log can now be filtered by
channels or groups of channels, using the
logger filter CLI commands.
> logger: Add channel-based filtering.

- configs/samples/iax.conf.sample
This improves the documentation for the bandwidth setting in iax.conf by making it clearer what the ramifications of this setting are. It also changes the sample default from low to high, since only high is compatible with good codecs that people will want to use in the vast majority of cases, and this is a common gotcha that trips up new users.
Resolves: #425
> configs: Improve documentation for bandwidth in iax.conf.

- apps/app_chanisavail.c
- apps/app_followme.c
- main/bridge.c
- main/bridge_basic.c
Fixes a crash due to a lack of proper reference on the nativeformats
object before passing it into ast_request().  Also found potentially
similar use case bugs in app_chanisavail.c, bridge.c, and bridge_basic.c
Fixes: #388
> app_followme.c: Grab reference on nativeformats before using it

- funcs/func_lock.c
> func_lock: Add missing see-also refs to documentation.

- contrib/scripts/live_ast
`astcachedir` (added in b0842713) was not added to `live_ast` so continued to point to the system `/var/cache` directory instead of the one in the live environment.
> live_ast: Add astcachedir to generated asterisk.conf.

- main/tcptls.c
- res/res_http_websocket.c
Additionally add a `assert()` to in the TLS client setup code to
ensure that hostname is set when it is supposed to be.
Fixes #433
> res_http_websocket.c: Set hostname on client for certificate validation.

- funcs/func_curl.c
I assume this was missed when initially converting to XML documentation and we've been kicking the can down the road since.
> func_curl.c: Remove CURLOPT() plaintext documentation.

- apps/app_authenticate.c
- apps/app_confbridge.c
- apps/app_playback.c
- apps/app_queue.c
- apps/app_read.c
- apps/app_skel.c
- apps/app_speech_utils.c
- main/app.c
- main/pbx_builtins.c
Any function or application that accepts a `&`-separated list of
filenames can now include a literal `&` in a filename by wrapping the
entire filename in single quotes, e.g.:
```
exten = _X.,n,Playback('https://example.com/sound.cgi?a=b&c=d'&hello-world)
```
Fixes #172
UpgradeNote: Ampersands in URLs passed to the `Playback()`,
`Background()`, `SpeechBackground()`, `Read()`, `Authenticate()`, or
`Queue()` applications as filename arguments can now be escaped by
single quoting the filename. Additionally, this is also possible when
using the `CONFBRIDGE` dialplan function, or configuring various
features in `confbridge.conf` and `queues.conf`.
> app.c: Allow ampersands in playback lists to be escaped.

- channels/chan_dahdi.c
- funcs/func_channel.c
- include/asterisk/frame.h
Certain channel options are not set anywhere or
exposed in any way to users, making them unusable. This exposes some of these options which make sense for users to manipulate at runtime.
Resolves: #442
> func_channel: Expose previously unsettable options.

- channels/sig_analog.c
When mwimonitor=yes is enabled for an FXO port,
the do_monitor thread will launch mwi_thread if it thinks there could be MWI on an FXO channel, due to the noise threshold being satisfied. This, in turns, calls
analog_ss_thread_start in sig_analog. However, unlike all other instances where __analog_ss_thread is called in sig_analog, this call path does not properly set pvt->ss_astchan to the Asterisk channel, which means that the Asterisk channel is NULL when __analog_ss_thread starts executing. As a result, the thread exits and the channel is never properly cleaned up by calling ast_hangup.
This caused issues with do_monitor on incoming calls, as it would think the channel was still owned even while receiving events, leading to an infinite barrage of warning messages; additionally, the …
> sig_analog: Fix channel leak when mwimonitor is enabled.

- build_tools/make_xml_documentation
If `LOCAL_MOD_SUBDIRS` contains absolute paths, do not prefix them with the path to Asterisk's source tree.
Fixes #142
> make_xml_documentation: Properly handle absolute LOCAL_MOD_SUBDIRS.

- res/res_pjsip_header_funcs.c
> res_pjsip_header_funcs.c: Check URI parameter length before copying.

- main/logger.c
- main/logger.xml
The `get_documentation` awk script will only extract the first DOCUMENTATION block that it finds in a given file. This is by design (9bc2127) to prevent AMI event documentation from being pulled in to the core.xml documentation file.
Because of this, the `LOG_GROUP` documentation added in 89709e2 was not being properly extracted and was missing fom the resulting XML documentation file. This commit moves the `LOG_GROUP` documentation to a separate `logger.xml` file.
> logger.c: Move LOG_GROUP documentation to dedicated XML file.

- contrib/scripts/ast_coredumper
Instead of searching for the asterisk binary and the modules in the
filesystem, we now get their locations, along with libdir, from
the coredump itself...
For the binary, we can use `gdb -c <coredump> ... "info proc exe"`.
gdb can print this even without having the executable and symbols.
Once we have the binary, we can get the location of the modules with
`gdb ... "print ast_config_AST_MODULE_DIR`
If there was no result then either it's not an asterisk coredump
or there were no symbols loaded.  Either way, it's not usable.
For libdir, we now run "strings" on the note0 section of the
coredump (which has the shared library -> memory address xref) and
search for "libasteriskssl|libasteriskpj", then take the dirname.
Since we're now getting everything from the coredump, it has to be
correct …
> ast_coredumper: Increase reliability

- apps/app_dial.c
Resolves: #462
UserNote: The option "j" is now available for the Dial application which uses the initial stream topology of the caller to create the outgoing channels.
> app_dial: Add option "j" to preserve initial stream topology of caller

- build_tools/make_xml_documentation
Although `make_xml_documentation`'s `print_dependencies` command was corrected by the previous fix (#461) for #142, the `create_xml` was not properly handling `LOCAL_MOD_SUBDIRS` XML documentation.
> make_xml_documentation: Really collect LOCAL_MOD_SUBDIRS documentation.

- main/manager.c
Improve the "manager show connected" CLI command
to clarify that the last two columns are permissions related, not counts, and use sufficient widths
to consistently display these values.
ASTERISK-30143 #close
Resolves: #482
> manager.c: Improve clarity of "manager show connected".

- configs/samples/pjproject.conf.sample
- res/res_pjproject.c
- third-party/pjproject/patches/0220-log-dropped-packet-in-debug.patch
Add patch to split the log level for invalid packets received on the signaling port.
The warning regarding the packet will move to level 2 so that it can still be displayed,
while the raw packet will be at level 4.
> res_pjsip: disable raw bad packet logging

- res/res_rtp_asterisk.c
When ICE is in use, we can prevent a possible DOS attack by allowing
DTLS protocol messages (client hello, etc) only from sources that
are in the active remote candidates list.
Resolves: GHSA-hxj9-xwr8-w8pq
> res_rtp_asterisk.c: Check DTLS packets against ICE candidate list

- res/res_pjsip_header_funcs.c
When updating an existing header the 'update' code incorrectly
just copied the new value into the existing buffer. If the
new value exceeded the available buffer size memory outside
of the buffer would be written into, potentially causing
a crash.
This change makes it so that the 'update' now duplicates
the new header value instead of copying it into the existing
buffer.
> res_pjsip_header_funcs: Duplicate new header value, don't copy.

- doc/CHANGES-staging/app_directory_skip_call.txt
- doc/CHANGES-staging/app_read_return_terminator.txt
- doc/CHANGES-staging/app_senddtmf_answer.txt
This should have been removed after the last release but
was missed.
> doc: Remove obsolete CHANGES-staging directrory

- include/asterisk/res_pjproject.h
- res/res_pjproject.c
- res/res_rtp_asterisk.c
* Since ICE candidates are used for the check and pjproject is
required to use ICE, res_rtp_asterisk was failing to compile
when pjproject wasn't available.  The check is now wrapped
with an #ifdef HAVE_PJPROJECT.
* The rtp->ice_active_remote_candidates container was being
used to check the address on incoming packets but that
container doesn't contain peer reflexive candidates discovered
during negotiation. This was causing the check to fail
where it shouldn't.  We now check against pjproject's
real_ice->rcand array which will contain those candidates.
* Also fixed a bug in ast_sockaddr_from_pj_sockaddr() where
we weren't zeroing out sin->sin_zero before returning.  This
was causing ast_sockaddr_cmp() to always return false when
one of the inputs was converted from a pj_sockaddr, even
if …
> res_rtp_asterisk: Fix regression issues with DTLS client check

- main/manager.c
Commit 424be345639d75c6cb7d0bd2da5f0f407dbd0bd5 introduced a regression by calling ast_free on memory allocated by realpath. This causes Asterisk to abort when executing this function. Since the memory is allocated by glibc, it should be freed using ast_std_free.
Resolves: #513
> manager.c: Fix regression due to using wrong free function.

- res/res_pjsip.c
- res/res_pjsip_nat.c
The `ast_sip_request_transport_details` must be zero initialized, otherwise this could lead to a SEGV.
Resolves: #509
> res_pjsip_nat: Fix potential use of uninitialized transport details

- menuselect/menuselect.c
Instead of using the same error message for
missing dependencies and conflicts, be specific
about what actually went wrong.
Resolves: #520
> menuselect: Use more specific error message.

- main/channel.c
- res/res_pjsip_session.c
This reverts commit 315eb551dbd18ecd424a2f32179d4c1f6f6edd26.
Over the past year, we've had several reports of "topology storms"
occurring where 2 external facing channels connected by one or more
local channels and bridges will get themselves in a state where
they continually send each other topology change requests.  This
usually manifests itself in no-audio calls and a flood of
"Exceptionally long queue length" messages.  It appears that this
commit is the cause so we're reverting it for now until we can
determine a more appropriate solution.
Resolves: #530
> Revert "core & res_pjsip: Improve topology change handling."

- funcs/func_frame_trace.c
- main/channel.c
This adds a simple CLI command that can be used for analyzing all frames currently queued to a channel.
A couple log messages are also adjusted to be more useful in tracing bridging problems.
Resolves: #533
> func_frame_trace: Add CLI command to dump frame queue.

- channels/chan_rtp.c
> chan_rtp.c: Change MulticastRTP nameing to avoid memory leak

- channels/chan_rtp.c
> chan_rtp.c: MulticastRTP missing refcount without codec option

- channels/chan_dahdi.c
- channels/chan_dahdi.h
This adds a CLI command to manually toggle the MWI status of a channel, useful for troubleshooting or resetting MWI devices, similar to the capabilities offered with SIP messaging to manually control MWI status.
UserNote: The 'dahdi set mwi' now allows MWI on channels to be manually toggled if needed for troubleshooting.
Resolves: #440
> chan_dahdi: Allow MWI to be manually toggled on channels.

- apps/app_voicemail.c
- contrib/ast-db-manage/voicemail/versions/1c55c341360f_remove_macrocontext_field.py
When app_macro was deprecated, the macrocontext column was removed from
the INSERT statement but the binds were not renumbered. This broke the
insert.
This change removes the macrocontext column via alembic and re-numbers
the existing columns in the INSERT.
Fixes: #527
UserNote: The fix requires removing the macrocontext column from the
voicemail_messages table in the voicemail database via alembic upgrade.
UpgradeNote: The fix requires that the voicemail database be upgraded via
alembic. Upgrading to the latest voicemail database via alembic will
remove the macrocontext column from the voicemail_messages table.
> app_voicemail_odbc: remove macrocontext from voicemail_messages table

- contrib/ast-db-manage/voicemail/versions/1c55c341360f_macrocontext_NoOp.py
Adding a NoOp alembic script for the voicemail database to maintain
version sync with other branches.
Fixes: #527
> app_voicemail: add NoOp alembic script to maintain sync

- res/res_calendar_icalendar.c
If libical fails to parse a calendar, print the error message it provdes.
Resolves: #492
> res_calendar_icalendar: Print iCalendar error on parsing failure.

- main/manager.c
Currently, a reload will always occur if the
Reload header is provided for the UpdateConfig
action. However, we should not be doing a reload
if the header value has a falsy value, per the
documentation, so this makes the reload behavior
consistent with the existing documentation.
Resolves: #551
> manager.c: Fix erroneous reloads in UpdateConfig.

- main/rtp_engine.c
> rtp_engine.c: Correct sample rate typo for L16/44100.

- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip_session.c
- res/res_pjsip_t38.c
Resolves a regression identified by @justinludwig involving the rendering of IPv6 addresses in outgoing SDP.
Also updates `media_address` on PJSIP endpoints so that if we are able to parse the configured value as an IP we store it in a format that we can directly use later. Based on my reading of the code it appeared that one could configure `media_address` as:
```
[foo]
type = endpoint
...
media_address = [2001:db8::]
```
And that value would be blindly copied into the outgoing SDP without regard to its format.
Fixes #541
> res_pjsip_session.c: Correctly format SDP connection addresses.

- configure
- configure.ac
- include/asterisk/autoconfig.h.in
- main/utils.c
FreeBSD has had kernel threads for 20+ years.
> main/utils: Simplify the FreeBSD ast_get_tid() handling

- bootstrap.sh
Bump up to the more commonly used and modern versions of
autoconf and automake.
> BuildSystem: Bump autotools versions on OpenBSD.

- res/res_pjsip_t38.c
The existing code prevented IPv6 addresses from being properly parsed.
Fixes #558
> res_pjsip_t38.c: Permit IPv6 SDP connection addresses.

- include/asterisk/strings.h
- main/utils.c
Given the scenario of passing an empty string to the ast_strsep functions the functions would return NULL instead of an empty string. This is counter to how strsep itself works.
This change alters the behavior of the functions to match that of strsep.
Fixes: #565
> utils: Make behavior of ast_strsep* match strsep.

- apps/app_amd.c
- codecs/codec_speex.c
- main/bridge.c
- main/bucket.c
- main/cdr.c
- main/channel.c
- main/codec.c
- main/config.c
- main/dns_core.c
- main/file.c
- main/format.c
- main/format_cache.c
- main/image.c
- main/indications.c
- main/loader.c
- main/manager.c
- main/message.c
- main/pbx.c
- main/pbx_app.c
- main/pbx_functions.c
- main/refer.c
- main/rtp_engine.c
- main/sorcery.c
- main/translate.c
- res/res_agi.c
- res/res_audiosocket.c
- res/res_clialiases.c
- res/res_http_websocket.c
- res/res_speech.c
When started with a verbose level of 3, asterisk can emit over 1500
verbose message that serve no real purpose other than to fill up
logs. When asterisk shuts down, it emits another 1100 that are of
even less use. Since the testsuite runs asterisk with a verbose
level of 3, and asterisk starts and stops for every one of the 700+
tests, the number of log messages is staggering.  Besides taking up
resources, it also makes it hard to debug failing tests.
This commit changes the log level for those verbose messages to 5
instead of 3 which reduces the number of log messages to only a
handful. Of course, NOTICE, WARNING and ERROR message are
unaffected.
There's also one other minor change...
ast_context_remove_extension_callerid2() logs a DEBUG message
instead of an ERROR if the extension …
> Reduce startup/shutdown verbose logging

- channels/pjsip/cli_commands.c
- main/rtp_engine.c
Under rare circumstances, it's possible for the original audio
session in the active_media_state default_session to be corrupted
instead of removed when switching to the t38/image media session
during fax negotiation.  This can cause a segfault when a "pjsip
show channelstats" attempts to print that audio media session's
rtp statistics.  In these cases, the active_media_state
topology is correctly showing only a single t38/image stream
so we now check that there's an audio stream in the topology
before attempting to use the audio media session to get the rtp
statistics.
Resolves: #592
> pjsip show channelstats: Prevent possible segfault when faxing

- res/res_rtp_asterisk.c
res_rtp_asterisk.c: Correct coefficient in MOS calculation.
Media Experience Score relies on incorrect pseudo_mos variable
calculation. According to forming an opinion section of the
documentation, calculation relies on ITU-T G.107 standard:
https://docs.asterisk.org/Deployment/Media-Experience-Score/#forming-an-opinion
ITU-T G.107 Annex B suggests to calculate MOS with a coefficient
"seven times ten to the power of negative six", 7 * 10^(-6). which
would mean 6 digits after the decimal point. Current implementation
has 7 digits after the decimal point, which downrates the calls.
Fixes: #597
> pseudo-MOS calculation formula change

- include/asterisk/strings.h
If a dynamic string is created with an initial length of 0, `ast_str_buffer(…)` will return an invalid pointer.
This was a secondary discovery when fixing #65.
> strings.h: Ensure ast_str_buffer(…) returns a 0 terminated string.

- main/translate.c
The new mode gives for each codec translation the actual real cost of microseconds per second cpu time taken. This allows to compare actual real cpu usage of translations and helps in evaluation of codec implementation changes regarding performance (regression testing)
sample output:
Resolves: #601
> translate.c: implement new direct comp table mode

- contrib/ast-db-manage/config/versions/24c12d8e9014_dummy_migration.py
This adds a dummy migration to 18 and 20 so that our alembic heads are synchronized across all supported branches.
In this case the migration we are stubbing (24c12d8e9014) is:
https://github.com/asterisk/asterisk/commit/775352ee6c2a5bcd4f0e3df51aee5d1b0abf4cbe
> alembic: Synchronize alembic heads between supported branches.

- Makefile
The default location for the stir_shaken cache is
/var/lib/asterisk/keys/stir_shaken/cache but we were only creating
/var/lib/asterisk/keys/stir_shaken on istall.  We now create
the cache sub-directory.
Resolves: #634
> Makefile: Add stir_shaken/cache to directories created on install

- res/res_stir_shaken/attestation_config.c
In as_check_common_config, we were calling ast_std_free on
raw_key but raw_key was allocated with ast_malloc so it
should be freed with ast_free.
Resolves: #636
> attestation_config.c: Use ast_free instead of ast_std_free

- contrib/ast-db-manage/config/versions/74dc751dfe8e_more_permission_boolean_columns.py
This migrates the relevant schema objects from the `('yes', 'no')` definition to the `('0', '1', 'off', 'on', 'false', 'true', 'yes', 'no')` one.
Fixes #617
> res_pjsip: Use consistent type for boolean columns.

- apps/app_voicemail.c
- configs/samples/voicemail.conf.sample
This adds an option to allow preventing callers from leaving messages marked as 'urgent'.
Resolves: #619
UserNote: The leaveurgent mailbox option can now be used to control whether callers may leave messages marked as 'Urgent'.
> app_voicemail: Allow preventing mark messages as urgent.

- apps/app_queue.c
Fixing bracket placement in the "queue add member" cli usage string.
> app_queue.c : fix "queue add member" usage string

- apps/app_voicemail.c
Most app_voicemail unit tests were not properly cleaning up after themselves after running. This led to test mailboxes lingering around in the system. It also meant that if any unit tests in app_voicemail that create mailboxes were executed and the module was not unloaded/loaded again prior to running the test_voicemail_vm_info unit test, Asterisk would segfault due to an attempt to copy a NULL string.
The load_config test did actually have logic to reinitialize the config after the test. However, this did not work in practice since load_config() would not reload the config since voicemail.conf had not changed during the test; thus, additional logic has been added to ensure that voicemail.conf is truly reloaded, after any unit tests which modify the users list.
This prevents the SEGV due …
> app_voicemail: Properly reinitialize config after unit tests.

- apps/app_dial.c
Add a timeout option to control the amount of time to wait if no early media is received before giving up. This allows aborting early if the destination
is not being responsive.
Resolves: #588
UserNote: The timeout argument to Dial now allows
specifying the maximum amount of time to dial if
early media is not received.
> app_dial: Add dial time for progress/ringing.

- res/res_monitor.c
Code was added in 030f7d41 to warn if an unrecognized option was passed to an application, but code in Monitor was taking advantage of the fact that the application would silently accept an invalid option.
We now recognize the invalid option but we don't do anything if it's set.
Fixes #639
> res_monitor.c: Don't emit a warning about 'X' being unrecognized.

- res/res_pjsip_session.c
In `handle_negotiated_sdp` the `pending_media_state->read_callbacks` must be reset before they are added in the SDP handlers in `handle_negotiated_sdp_session_media`. Otherwise, old callbacks for removed streams and file descriptors could be added to the channel and Asterisk would poll on non-existing file descriptors.
Resolves: #611
> res_pjsip_session: Reset pending_media_state->read_callbacks

- third-party/pjproject/pjproject-2.14.1.tar.bz2.md5
- third-party/pjproject/pjproject-2.14.tar.bz2.md5
- third-party/versions.mak
Fixes: asterisk#648
UserNote: Bundled pjproject has been upgraded to 2.14.1. For more
information visit pjproject Github page: https://github.com/pjsip/pjproject/releases/tag/2.14.1
> Upgrade bundled pjproject to 2.14.1

- main/manager.c
This adds a CLI command that can be used to manually kick specific AMI sessions.
Resolves: #485
UserNote: The "manager kick session" CLI command now allows kicking a specified AMI session.
> manager.c: Add CLI command to kick AMI sessions.

- main/pbx_variables.c
It is possible for dialplan to result in an infinite recursion of variable substitution, which eventually leads to stack overflow. If we detect this, abort
substitution and log an error for the user to fix
the broken dialplan.
Resolves: #480
UpgradeNote: The maximum amount of dialplan recursion using variable substitution (such as by using EVAL_EXTEN) is capped at 15.
> pbx_variables.c: Prevent SEGV due to stack overflow.

- main/manager.c
manager.c: Add new parameter 'PreDialGoSub' to Originate AMI action
The action originate does not has the ability to run an subroutine at initial channel, like the Aplication Originate. This update give this ability for de action originate too.
For example, we can run a routine via Gosub on the channel to request an automatic answer, so the caller does not need to accept the call when using the originate command via manager, making the operation more efficient.
UserNote: When using the Originate AMI Action, we now can pass the PreDialGoSub parameter, instructing the asterisk to perform an subrouting at channel before call start. With this parameter an call initiated by AMI can request the channel to start the call automaticaly, adding a SIP header to using GoSUB, instructing to autoanswer …
> manager.c: Add new parameter 'PreDialGoSub' to Originate AMI action.

- res/res_ari.c
When ARI debug is enabled the logs will now output http method and the uri.
Fixes: #666
> res_ari.c: Add additional output to ARI requests when debug is enabled

- channels/chan_dahdi.c
Commit 729cb1d390b136ccc696430aa5c68d60ea4028be added logic to retry opening DAHDI channels on "dahdi restart" if they failed initially, up to 1,000 times in a loop, to address cases where the channel was still in use. However, this retry loop does not use the actual error, which means chan_dahdi will also retry opening nonexistent channels 1,000 times per channel, causing a flood of unnecessary warning logs for an operation that will never succeed, with tens or hundreds of thousands of open attempts being made.
The original patch would have been more targeted if it only retried on the specific relevant error (likely EBUSY, although it's hard to say since the original issue is no longer available).
To avoid the problem above while avoiding the possibility of breakage, this skips the retry …
> chan_dahdi: Don't retry opening nonexistent channels on restart.

- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/cf150a175fd3_add_match_request_uri_attribute_to_.py
- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip_endpoint_identifier_ip.c
Add ability to match against PJSIP request URI.
Use the 'request_uri' identifier in the identify_by field.
Fixes: #599
> res_pjsip_endpoint_identifier_ip: Endpoint identifier request URI

- main/cli.c
> cli.c: `core show channels concise` is not really deprecated.

- apps/app_mixmonitor.c
- apps/app_stack.c
- channels/chan_iax2.c
- main/pbx_builtins.c
- res/res_fax.c
There were a few references in the embedded documentation XML
where the case didn't match or where the referenced app or function
simply didn't exist any more.  These were causing 404 responses
in docs.asterisk.org.
> Fix incorrect application and function documentation references - 21 and master

- res/res_stir_shaken/common_config.h
- res/res_stir_shaken/crypto_utils.c
- res/res_stir_shaken/crypto_utils.h
- res/res_stir_shaken/verification_config.c
* OpenSSL 1.0.2 doesn't support X509_get0_pubkey so we now use
X509_get_pubkey.  The difference is that X509_get_pubkey requires
the caller to free the EVP_PKEY themselves so we now let
RAII_VAR do that.
* OpenSSL 1.0.2 doesn't support upreffing an X509_STORE so we now
wrap it in an ao2 object.
* OpenSSL 1.0.2 doesn't support X509_STORE_get0_objects to get all
the certs from an X509_STORE and there's no easy way to polyfill
it so the CLI commands that list profiles will show a "not
supported" message instead of listing the certs in a store.
Resolves: #676
> res_stir_shaken:  Fix compilation for CentOS7 (openssl 1.0.2)

- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/d5122576cca8_add_transport_attribute_to_identify.py
- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip_endpoint_identifier_ip.c
Add a new identify_by option to res_pjsip_endpoint_identifier_ip called 'transport' this matches endpoints based on the bound ip address (local) instead of the 'ip' option, which matches on the source ip address (remote).
Fixes: #672
> res_pjsip_endpoint_identifier_ip: Add endpoint identifier transport address

- funcs/func_callerid.c
Emit a warning if REDIRECTING(reason) is set to an invalid reason, consistent with what happens when
REDIRECTING(orig-reason) is set to an invalid reason.
Resolves: #683
> func_callerid: Emit warning if invalid redirecting reason set.

- main/rtp_engine.c
- main/stun.c
rtp_engine.c and stun.c were calling ast_register_cleanup which
is skipped if any loadable module can't be cleanly unloaded
when asterisk shuts down.  Since this will always be the case,
their cleanup functions never get run.  In a practical sense
this makes no difference since asterisk is shutting down but if
you're in development mode and trying to use the leak sanitizer,
the leaks from both of those modules clutter up the output.
> rtp_engine and stun: call ast_register_atexit instead of ast_register_cleanup

- main/channel.c
- main/file.c
Silently ignore AST_CONTROL_PROGRESS where appropriate, as most control frames already are.
Resolves: #696
> file.c, channel.c: Don't emit warnings if progress received.

- apps/app_queue.c
The existing code sets the queue strategy to `ringall` but it is then immediately overwritten with an invalid one.
Fixes #707
> app_queue.c: Properly handle invalid strategies from realtime.

- include/asterisk/logger.h
If you're tracing a large function that may call another function
multiple times in different circumstances, it can be difficult to
see from the trace output exactly which location that function
was called from.  There's no good way to automatically determine
the calling location.  SCOPE_CALL and SCOPE_CALL_WITH_RESULT
simply print out a trace line before and after the call.
The difference between SCOPE_CALL and SCOPE_CALL_WITH_RESULT is
that SCOPE_CALL ignores the function's return value (if any) where
SCOPE_CALL_WITH_RESULT allows you to specify the type of the
function's return value so it can be assigned to a variable.
SCOPE_CALL_WITH_INT_RESULT is just a wrapper for SCOPE_CALL_WITH_RESULT
and the "int" return type.
> logger.h:  Add SCOPE_CALL and SCOPE_CALL_WITH_RESULT

- channels/chan_dahdi.c
- funcs/func_callerid.c
- include/asterisk/callerid.h
- main/callerid.c
Commit f2f397c1a8cc48913434ebb297f0ff50d96993db previously made it possible to send Caller ID parameters to FXS stations which, prior to that, could not be sent.
This change is complementary in that we now handle receiving all these parameters on FXO lines and provide these up to the dialplan, via chan_dahdi. In particular:
* If a redirecting reason is provided, the channel's redirecting reason is set. No redirecting number is set, since there is no parameter for this in the Caller ID protocol, but the reason can be checked to determine if and why a call was forwarded.
* If the Call Qualifier parameter is received, the Call Qualifier variable is set.
* Some comments have been added to explain why some of the code is the way it is, to assist other people looking at it.
With this change, …
> callerid.c: Parse previously ignored Caller ID parameters.

- main/sorcery.c
sorcery.c: Fixed crash error when executing "module reload" with sorcery cache registration and res_prometeus
Fixed crash error when cli "module reload".
The error appears when compiling with res_prometheus and using the sorcery memory cache for registrations
> sorcery.c: Fixed crash error when executing "module reload" with sorcery cache registration and res_prometeus

- configs/samples/stir_shaken.conf.sample
- res/res_pjsip_stir_shaken.c
- res/res_stir_shaken/attestation.c
- res/res_stir_shaken/common_config.c
- res/res_stir_shaken/common_config.h
- res/res_stir_shaken/tn_config.c
- res/res_stir_shaken/verification.c
* Fixed possible memory leak in tn_config:tn_get_etn() where we
weren't releasing etn if tn or eprofile were null.
* We now canonicalize TNs before using them for lookups or adding
them to Identity headers.
* Fixed a typo in stir_shaken.conf.sample.
Resolves: #716
> stir_shaken:  Fix memory leak, typo in config, tn canonicalization

- include/asterisk/iostream.h
- main/iostream.c
- main/tcptls.c
If the hostname field of the ast_tcptls_session_args structure is
set (which it is for websocket client connections), that hostname
will now automatically be used in an SNI TLS extension in the client
hello.
Resolves: #713
UserNote: Secure websocket client connections now send SNI in
the TLS client hello.
> tcptls/iostream:  Add support for setting SNI on client TLS connections - cert/18.9 only

- include/asterisk/iostream.h
- main/iostream.c
- main/tcptls.c
If the hostname field of the ast_tcptls_session_args structure is
set (which it is for websocket client connections), that hostname
will now automatically be used in an SNI TLS extension in the client
hello.
Resolves: #713
UserNote: Secure websocket client connections now send SNI in
the TLS client hello.
> tcptls/iostream:  Add support for setting SNI on client TLS connections

- res/res_pjsip_sdp_rtp.c
First rtp activity check was performed after 500ms regardless of the rtp_timeout setting. Having a call in ringing state for more than rtp_timeout and the first rtp package is received more than 500ms after sdp negotiation and before the rtp_timeout, erronously caused the call to be hungup. Changed to perform the first rtp inactivity check after the timeout setting preventing calls to be disconnected before the rtp_timeout has elapsed since sdp negotiation.
Fixes #710
> Initial RTP inactivity check must consider the rtp_timeout setting.

- funcs/func_sayfiles.c
- main/say.c
Some of the money announcements can be off by one cent, due to the use of floating point in the money calculations, which is bad for obvious reasons.
This replaces floating point with simple string parsing to ensure the cents value is converted accurately.
Resolves: #525
> say.c: Fix cents off-by-one due to floating point rounding.

- apps/app_record.c
This adds the RECORD_TIME variable to Record(),
which is set to the recording duration before
the application returns.
Resolves: #548
> app_record: Add RECORD_TIME output variable.

- include/asterisk/logger.h
- main/asterisk.c
- main/logger.c
Add unique verbose prefixes for levels higher than 4, so that these can be visually differentiated from each other.
Resolves: #721
> logger: Add unique verbose prefixes for levels 5-10.

- res/res_pjsip_logger.c
Currently, reloading res_pjsip will cause logging
to be disabled. This is because logging can also
be controlled via the debug option in pjsip.conf
and this defaults to "no".
To improve this, logging is no longer disabled on
reloads if logging had not been previously
enabled using the debug option from the config.
This ensures that logging enabled from the CLI
will persist through a reload.
ASTERISK-29912 #close
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/19575
Resolves: #246
UserNote: Issuing "pjsip reload" will no longer disable logging if it was previously enabled from the CLI.
> res_pjsip_logger: Preserve logging state on reloads.

- res/stasis/control.c
Include `signal.h` to avoid the following build failure with uclibc-ng raised since https://github.com/asterisk/asterisk/commit/2694792e13c7f3ab1911c4a69fba0df32c544177:
```
stasis/control.c: In function 'exec_command_on_condition': stasis/control.c:313:3: warning: implicit declaration of function 'pthread_kill'; did you mean 'pthread_yield'? [-Wimplicit-function-declaration]
313 |   pthread_kill(control->control_thread, SIGURG);
|   ^~~~~~~~~~~~
|   pthread_yield
stasis/control.c:313:41: error: 'SIGURG' undeclared (first use in this function)
313 |   pthread_kill(control->control_thread, SIGURG);
|                                         ^~~~~~
```
Fixes:  #729
> res/stasis/control.c: include signal.h

- include/asterisk/rtp_engine.h
- main/rtp_engine.c
- res/res_pjsip_sdp_rtp.c
- res/res_rtp_asterisk.c
Add RFC2833 DTMF support for 16K, 24K, and 32K bitrate codecs.
Asterisk currently treats RFC2833 Digits as a single rtp payload type
with a fixed bitrate of 8K.  This change would expand that to 8, 16,
24 and 32K.
This requires checking the offered rtp types for any of these bitrates
and then adding an offer for each (if configured for RFC2833.)  DTMF
generation must also be changed in order to look at the current outbound
codec in order to generate appropriately timed rtp.
For cases where no outgoing audio has yet been sent prior to digit
generation, Asterisk now has a concept of a 'preferred' codec based on
offer order.
On inbound calls Asterisk will mimic the payload types of the RFC2833 digits.
On outbound calls Asterisk will choose the next free payload types starting
with 101. …
> rtp_engine: add support for multirate RFC2833 digits

- include/asterisk/file.h
- main/file.c
> file.h: Rename function argument to avoid C++ keyword clash.

- main/asterisk.c
> asterisk.c: Don't log an error if .asterisk_history does not exist.

- main/xml.c
- res/res_calendar_caldav.c
Two functions are deprecated as of libxml2 2.12:
* xmlSubstituteEntitiesDefault
* xmlParseMemory
So we update those with supported API.
Additionally, `res_calendar_caldav` has been updated to use libxml2's xmlreader API instead of the SAX2 API which has always felt a little hacky (see deleted comment block in `res_calendar_caldav.c`).
The xmlreader API has been around since libxml2 2.5.0 which was released in 2003.
Fixes #725
> xml.c: Update deprecated libxml2 API usage.

- main/asterisk.c
Since Asterisk 19 it is possible to cache recorded files into another directory [1] [2].
Show configured location of cache dir in CLI's core show settings.
[1] ASTERISK-29143
[2] b08427134fd51bb549f198e9f60685f2680c68d7
> Show configured cache dir

- main/manager.c
> manager.c: Properly terminate `CoreShowChannelMap` event.

- channels/chan_pjsip.c
- channels/pjsip/dialplan_functions.c
- channels/pjsip/dialplan_functions_doc.xml
Various SIP headers permit a URI to be prefaced with a `display-name` production that can include characters (like commas and parentheses) that are problematic for Asterisk's dialplan parser and, specifically in the case of this patch, the PJSIP_PARSE_URI function.
This patch introduces a new function - `PJSIP_PARSE_URI_FROM` - that behaves identically to `PJSIP_PARSE_URI` except that the first argument is now a variable name and not a literal URI.
Fixes #756
> pjsip: Add PJSIP_PARSE_URI_FROM dialplan function.

- main/pbx.c
The current width for "extension" is 20 and "device state id" is 20, which is too small.
The "extension" field contains "ext"@"context", so 20 characters is not enough.
The "device state id" field, for example for Queue pause state contains Queue:"queue_name"_pause_PSJIP/"endpoint", so the 20 characters is not enough.
Increase the width of "extension" field to 30 characters and the width of the "device state id" field to 60 characters.
Resolves: https://github.com/asterisk/asterisk/issues/770
UserNote: The fields width of "core show hints" were increased.
The width of "extension" field to 30 characters and
the width of the "device state id" field to 60 characters.
> pbx.c: expand fields width of "core show hints"

- apps/app_queue.c
- configs/samples/queues.conf.sample
- contrib/ast-db-manage/config/versions/2b7c507d7d12_add_queue_log_option_log_restricted_.py
Add a queue option log-restricted-caller-id to strip the Caller ID when storing the ENTERQUEUE event
in the queue log if the Caller ID is restricted.
Resolves: #765
UpgradeNote: Add a new column to the queues table:
queue_log_option_log_restricted ENUM('0','1','off','on','false','true','no','yes')
to control whether the Restricted Caller ID will be stored in the queue log.
UserNote: Add a Queue option log-restricted-caller-id to control whether the Restricted Caller ID
will be stored in the queue log.
If log-restricted-caller-id=no then the Caller ID will be stripped if the Caller ID is restricted.
> app_queue:  Add option to not log Restricted Caller ID to queue_log

- apps/app_voicemail.c
- configs/samples/voicemail.conf.sample
- main/app.c
This commit adds a new voicemail.conf option 'odbc_audio_on_disk'
which when set causes the ODBC variant of app_voicemail to leave
the message and greeting audio files on disk and only store the
message metadata in the database.  This option came from a concern
that the database could grow to large and cause remote access
and/or replication to become slow.  In a clustering situation
with this option, all asterisk instances would share the same
database for the metadata and either use a shared filesystem
or other filesystem replication service much more suitable
for synchronizing files.
The changes to app_voicemail to implement this feature were actually
quite small but due to the complexity of the module, the actual
source code changes were greater.  They fall into the following …
> app_voicemail_odbc: Allow audio to be kept on disk

- apps/app_voicemail.c
- configs/samples/voicemail.conf.sample
- main/app.c
This commit adds a new voicemail.conf option 'odbc_audio_on_disk'
which when set causes the ODBC variant of app_voicemail to leave
the message and greeting audio files on disk and only store the
message metadata in the database.  This option came from a concern
that the database could grow to large and cause remote access
and/or replication to become slow.  In a clustering situation
with this option, all asterisk instances would share the same
database for the metadata and either use a shared filesystem
or other filesystem replication service much more suitable
for synchronizing files.
The changes to app_voicemail to implement this feature were actually
quite small but due to the complexity of the module, the actual
source code changes were greater.  They fall into the following …
> app_voicemail_odbc: Allow audio to be kept on disk - 18,20

- main/stasis_channels.c
Whenver a new channel snapshot is created or when a channel is
destroyed, we need to delete any existing channel snapshot from
the snapshot cache.  Historically, we used the channel->snapshot
pointer to delete any existing snapshots but this has two issues.
First, if something (possibly ast_channel_internal_swap_snapshots)
sets channel->snapshot to NULL while there's still a snapshot in
the cache, we wouldn't be able to delete it and it would be orphaned
when the channel is destroyed.  Since we use the cache to list
channels from the CLI, AMI and ARI, it would appear as though the
channel was still there when it wasn't.
Second, since there are actually two caches, one indexed by the
channel's uniqueid, and another indexed by the channel's name,
deleting from the caches by pointer requires …
> stasis_channels: Use uniqueid and name to delete old snapshots

- include/asterisk/logger.h
> logger.h: Include SCOPE_CALL_WITH_INT_RESULT() in non-dev-mode builds.

- res/res_pjsip/security_agreements.c
- res/res_pjsip_outbound_registration.c
The `Require: mediasec` and `Proxy-Require: mediasec` headers need
to be sent whenever we send `Security-Client` or `Security-Verify`
headers but the logic to do that was only in add_security_headers()
in res_pjsip_outbound_register.  So while we were sending them on
REGISTER requests, we weren't sending them on INVITE requests.
This commit moves the logic to send the two headers out of
res_pjsip_outbound_register:add_security_headers() and into
security_agreement:ast_sip_add_security_headers().  This way
they're always sent when we send `Security-Client` or
`Security-Verify`.
Resolves: #789
> security_agreement.c: Always add the Require and Proxy-Require headers

- apps/app_voicemail.c
- configs/samples/voicemail.conf.sample
- include/asterisk/logger.h
- main/app.c
In order to get the voicemail odbc commit into certified/18.9, earlier commits were also required.
- **app_voicemail.c: Completely resequence mailbox folders.**
- **logger.h:  Add SCOPE_CALL and SCOPE_CALL_WITH_RESULT**
- **app_voicemail_odbc: Allow audio to be kept on disk**
- **logger.h: Include SCOPE_CALL_WITH_INT_RESULT() in non-dev-mode builds.**
> app_voicemail_odbc: Allow audio to be kept on disk - cert-18.9

- contrib/ast-db-manage/config/versions/2b7c507d7d12_add_queue_log_option_log_restricted_.py
Remove duplicate creation of ast_bool_values from
2b7c507d7d12_add_queue_log_option_log_restricted_.py.  This was
causing alembic upgrades to fail since the enum was already created
in fe6592859b85_fix_mwi_subscribe_replaces_.py back in 2018.
Resolves: #797
> ast-db-manage: Remove duplicate enum creation

- include/asterisk/rtp_engine.h
- res/res_pjsip_sdp_rtp.c
- res/res_rtp_asterisk.c
After change made in 624f509 to add support for non 8K RFC 4733/2833 digits,
Asterisk would only accept RFC 4733/2833 offers that matched the sample rate of
the negotiated codec(s).
This change allows Asterisk to accept 8K RFC 4733/2833 offers if the UAC
offfers 8K RFC 4733/2833 but negotiates for a non 8K bitrate codec.
A number of corresponding tests in tests/channels/pjsip/dtmf_sdp also needed to
be re-written to allow for these scenarios.
Fixes: #776
> res_pjsip_sdp_rtp: Add support for default/mismatched 8K RFC 4733/2833 digits

- res/res_pjsip_path.c
When using the PJSIP_DIAL_CONTACTS() function for use in the Dial()
command, the contacts are returned in text form, so the input to
the path_outgoing_request() function is a contact value of NULL.
The issue was reported in ASTERISK-28211, but was not actually fixed
in ASTERISK-30100. This fix brings back the code that was previously
removed and adds code to search for a contact to extract the path
value from it.
> res_pjsip_path.c: Fix path when dialing using PJSIP_DIAL_CONTACTS()

- res/res_pjsip_sdp_rtp.c
res_pjsip_sdp_rtp.c: Fix DTMF Handling in Re-INVITE with dtmf_mode set to auto
When the endpoint dtmf_mode is set to auto, a SIP request is sent to the UAC, and the SIP SDP from the UAC does not include the telephone-event. Later, the UAC sends an INVITE, and the SIP SDP includes the telephone-event. In this case, DTMF should be sent by RFC2833 rather than using inband signaling.
Resolves: asterisk#826
> res_pjsip_sdp_rtp.c: Fix DTMF Handling in Re-INVITE with dtmf_mode set to auto

- res/res_stasis.c
- res/stasis/control.c
- res/stasis/control.h
Previously, on command execution, the control thread was awoken by
sending a SIGURG. It was found that this still resulted in some
instances where the thread was not immediately awoken.
This change instead sends a null frame to awaken the control thread,
which awakens the thread more consistently.
Resolves: #801
> res_stasis: fix intermittent delays on adding channel to bridge

- main/manager.c
Added Reload and DBdeltree to the list of dialplan application that
can't be executed via the Originate manager action without also
having write SYSTEM permissions.
Added CURL, DB*, FILE, ODBC and REALTIME* to the list of dialplan
functions that can't be executed via the Originate manager action
without also having write SYSTEM permissions.
If the Queue application is attempted to be run by the Originate
manager action and an AGI parameter is specified in the app data,
it'll be rejected unless the manager user has either the AGI or
SYSTEM permissions.
Resolves: #GHSA-c4cg-9275-6w44
> manager.c: Add entries to Originate blacklist

- configure
- configure.ac
source is a bash concept, so when /bin/sh points to another shell the existing construct won't work.
Reference: https://bugs.gentoo.org/927055
> configure:  Use . file rather than source file.

- cel/cel_manager.c
- channels/chan_pjsip.c
- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/655054a68ad5_add_pjsip_tenantid.py
- funcs/func_channel.c
- include/asterisk/cdr.h
- include/asterisk/cel.h
- include/asterisk/channel.h
- include/asterisk/channel_internal.h
- include/asterisk/event_defs.h
- include/asterisk/res_pjsip.h
- include/asterisk/stasis_channels.h
- main/cdr.c
- main/cel.c
- main/channel.c
- main/channel_internal_api.c
- main/cli.c
- main/event.c
- main/manager_channels.c
- main/stasis_channels.c
- res/ari/ari_model_validators.c
- res/ari/ari_model_validators.h
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_configuration.c
- rest-api/api-docs/channels.json
This patch introduces a new identifier for channels: tenantid. It's
a stringfield on the channel that can be used for general purposes. It
will be inherited by other channels the same way that linkedid is.
You can set tenantid in a few ways. The first is to set it in the
dialplan with the Set and CHANNEL functions:
exten => example,1,Set(CHANNEL(tenantid)=My tenant ID)
It can also be accessed via CHANNEL:
exten => example,2,NoOp(CHANNEL(tenantid))
Another method is to use the new tenantid option for pjsip endpoints in
pjsip.conf:
[my_endpoint]
type=endpoint
tenantid=My tenant ID
This is considered the best approach since you will be able to see the
tenant ID as early as the Newchannel event.
It can also be set using set_var in pjsip.conf on the endpoint like
setting other channel …
> channel: Add multi-tenant identifier. cert-18.9

- cel/cel_manager.c
- channels/chan_pjsip.c
- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/655054a68ad5_add_pjsip_tenantid.py
- funcs/func_channel.c
- include/asterisk/cdr.h
- include/asterisk/cel.h
- include/asterisk/channel.h
- include/asterisk/channel_internal.h
- include/asterisk/event_defs.h
- include/asterisk/res_pjsip.h
- include/asterisk/stasis_channels.h
- main/cdr.c
- main/cel.c
- main/channel.c
- main/channel_internal_api.c
- main/cli.c
- main/event.c
- main/manager_channels.c
- main/stasis_channels.c
- res/ari/ari_model_validators.c
- res/ari/ari_model_validators.h
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_configuration.c
- rest-api/api-docs/channels.json
This patch introduces a new identifier for channels: tenantid. It's
a stringfield on the channel that can be used for general purposes. It
will be inherited by other channels the same way that linkedid is.
You can set tenantid in a few ways. The first is to set it in the
dialplan with the Set and CHANNEL functions:
exten => example,1,Set(CHANNEL(tenantid)=My tenant ID)
It can also be accessed via CHANNEL:
exten => example,2,NoOp(CHANNEL(tenantid))
Another method is to use the new tenantid option for pjsip endpoints in
pjsip.conf:
[my_endpoint]
type=endpoint
tenantid=My tenant ID
This is considered the best approach since you will be able to see the
tenant ID as early as the Newchannel event.
It can also be set using set_var in pjsip.conf on the endpoint like
setting other channel …
> channel: Add multi-tenant identifier. cert-20.7

- cel/cel_manager.c
- channels/chan_pjsip.c
- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/655054a68ad5_add_pjsip_tenantid.py
- funcs/func_channel.c
- include/asterisk/cdr.h
- include/asterisk/cel.h
- include/asterisk/channel.h
- include/asterisk/channel_internal.h
- include/asterisk/event_defs.h
- include/asterisk/res_pjsip.h
- include/asterisk/stasis_channels.h
- main/cdr.c
- main/cel.c
- main/channel.c
- main/channel_internal_api.c
- main/cli.c
- main/event.c
- main/manager_channels.c
- main/stasis_channels.c
- res/ari/ari_model_validators.c
- res/ari/ari_model_validators.h
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_configuration.c
- rest-api/api-docs/channels.json
This patch introduces a new identifier for channels: tenantid. It's
a stringfield on the channel that can be used for general purposes. It
will be inherited by other channels the same way that linkedid is.
You can set tenantid in a few ways. The first is to set it in the
dialplan with the Set and CHANNEL functions:
exten => example,1,Set(CHANNEL(tenantid)=My tenant ID)
It can also be accessed via CHANNEL:
exten => example,2,NoOp(CHANNEL(tenantid))
Another method is to use the new tenantid option for pjsip endpoints in
pjsip.conf:
[my_endpoint]
type=endpoint
tenantid=My tenant ID
This is considered the best approach since you will be able to see the
tenant ID as early as the Newchannel event.
It can also be set using set_var in pjsip.conf on the endpoint like
setting other channel …
> channel: Add multi-tenant identifier.

- main/manager.c
If you run an AMI CoreShowChannelMap on a channel that isn't in a
bridge and you're in DEVMODE, you can get a FRACK because the
bridge id is empty.  We now simply return an empty list for that
request.
> manager.c: Fix FRACK when doing CoreShowChannelMap in DEVMODE

- channels/pjsip/dialplan_functions_doc.xml
- configs/samples/extensions.conf.sample
- configs/samples/pjsip.conf.sample
- configs/samples/pjsip_notify.conf.sample
- res/res_pjsip_notify.c
Add dialplan application PJSIPNOTIFY to send either pre-configured
NOTIFY messages from pjsip_notify.conf or with headers defined in
dialplan.
Also adds the ability to send pre-configured NOTIFY commands to a
channel via the CLI.
Resolves: #799
UserNote: The new CLI command syntax is
pjsip send notify <option> channel <channel>
> res_pjsip_notify: add dialplan application

- addons/chan_mobile.c
On modern Bluetooth devices or lower-powered asterisk servers, decreasing the channel frame size significantly improves latency and delay on outbound calls with only a mild sacrifice to the quality of the call (the frame size before was massive overkill to begin with)
Before changing this line, outgoing calls through chan_mobile had around a 15-20 second delay in transmission of the asterisk phone's voice to the mobile phone when playing outgoing calls, but after the patch has close to no latency in transmission.
> chan_mobile: decrease CHANNEL_FRAME_SIZE to prevent delay

- main/rtp_engine.c
- res/res_pjsip_sdp_rtp.c
PR #700 added a preferred_format for the struct ast_rtp_codecs,
but when set the preferred_format it leaks an astobj2 ast_format.
In the next code
ast_rtp_codecs_set_preferred_format(&codecs, ast_format_cap_get_format(joint, 0));
both functions ast_rtp_codecs_set_preferred_format
and ast_format_cap_get_format increases the ao2 reference count.
Fixes: #856
> res_pjsip_sdp_rtp fix leaking astobj2 ast_format

- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip/security_agreements.c
- res/res_pjsip_outbound_registration.c
* A static array of security mechanism type names was created.
* ast_sip_str_to_security_mechanism_type() was refactored to do
a lookup in the new array instead of using fixed "if/else if"
statments.
* security_mechanism_to_str() and ast_sip_security_mechanisms_to_str()
were refactored to use ast_str instead of a fixed length buffer
to store the result.
* ast_sip_security_mechanism_type_to_str was removed in favor of
just referencing the new type name array.  Despite starting with
"ast_sip_", it was a static function so removing it doesn't affect
ABI.
* Speaking of "ast_sip_", several other static functions that
started with "ast_sip_" were renamed to avoid confusion about
their public availability.
* A few VECTOR free loops were replaced with AST_VECTOR_RESET().
* Fixed a meomry leak in …
> security_agreements.c: Refactor the to_str functions and fix a few other bugs

- include/asterisk/rtp_engine.h
- main/rtp_engine.c
- res/res_pjsip_sdp_rtp.c
- res/res_rtp_asterisk.c
When Asterisk sends an offer to Bob that includes 48K and 8K codecs with
matching 4733 offers, Bob may want to use the 48K audio codec but can not
accept 48K digits and so negotiates for a mixed set.
Asterisk will now check Bob's offer to make sure Bob has indicated this is
acceptible and if not, will use Bob's preference.
Fixes: #847
> res_pjsip_sdp_rtp: Use negotiated DTMF Payload types on bitrate mismatch

- apps/app_voicemail.c
When commit e8c9cb80 was cherry-picked in from master, the
fact that the 20 and 18 branches still had the old "macrocontext"
column wasn't taken into account so the number of named parameters
didn't match the number of '?' placeholders.  They do now.
We also now use ast_asprintf to create the full mailbox query SQL
statement instead of trying to calculate the proper length ourselves.
Resolves: #831
> app_voicemail: Fix sql insert mismatch caused by cherry-pick

- main/dns_core.c
- res/res_resolver_unbound.c
The ub_result pointer passed to unbound_resolver_callback by
libunbound can be NULL if the query was for something malformed
like `.1` or `[.1]`.  If it is, we now set a 'ns_r_formerr' result
and return instead of crashing with a SEGV.  This causes pjproject
to simply cancel the transaction with a "No answer record in the DNS
response" error.  The existing "off nominal" unit test was also
updated to check this condition.
Although not necessary for this fix, we also made
ast_dns_resolver_completed() tolerant of a NULL result.
Resolves: GHSA-v428-g3cw-7hv9
> res_resolver_unbound: Test for NULL ub_result in unbound_resolver_callback

- apps/app_broadcast.c
- apps/app_chanspy.c
ChanSpy(${channel}, qEoSw): because flags set o, ast_audiohook_set_frame_feed_direction(audiohook, AST_AUDIOHOOK_DIRECTION_READ); this will effect whisper audiohook and spy audiohook, this makes writing frame to whisper audiohook impossible. So add function start_whispering to starting whisper audiohook.
Resolves: #876
> app_chanspy.c: resolving the issue writing frame to whisper audiohook.

- res/res_stir_shaken/verification.c
verification.c had an include for jansson.h left over from previous
versions of the module.  Since res_stir_shaken no longer has a
dependency on jansson, the bundled version wasn't added to GCC's
include path so if you didn't also have a jansson development package
installed, the compile would fail.  Removing the stale include
was the only thing needed.
Resolves: #889
> res_stir_shaken: Remove stale include for jansson.h in verification.c

- main/db.c
- tests/test_db.c
- tests/test_media_cache.c
Consumers like media_cache have been running into issues with
the previous astdb "/family/key" limit of 253 bytes when needing
to store things like long URIs.  An Amazon S3 URI is a good example
of this.  Now, instead of using a static 256 byte buffer for
"/family/key", we use ast_asprintf() to dynamically create it.
Both test_db.c and test_media_cache.c were also updated to use
keys/URIs over the old 253 character limit.
Resolves: #881
UserNote: The `ast_db_*()` APIs have had the 253 byte limit on
"/family/key" removed and will now accept families and keys with a
total length of up to SQLITE_MAX_LENGTH (currently 1e9!).  This
affects the `DB*` dialplan applications, dialplan functions,
manager actions and `databse` CLI commands.  Since the
media_cache also uses the `ast_db_*()` APIs, you …
> db.c: Remove limit on family/key length

- apps/app_playback.c
- main/pbx_builtins.c
The app is actually named "BackGround" but several references
in XML documentation were spelled "Background" with the lower
case "g".  This was causing documentation links to return
"not found" messages.
> Fix application references to Background

- res/res_stir_shaken/common_config.c
- res/res_stir_shaken/common_config.h
- res/res_stir_shaken/tn_config.c
attest_level, send_mky and check_tn_cert_public_url weren't
propagating correctly from the attestation object to the profile
and tn.
* In the case of attest_level, the enum needed to be changed
so the "0" value (the default) was "NOT_SET" instead of "A".  This
now allows the merging of the attestation object, profile and tn
to detect when a value isn't set and use the higher level value.
* For send_mky and check_tn_cert_public_url, the tn default was
forced to "NO" which always overrode the profile and attestation
objects.  Their defaults are now "NOT_SET" so the propagation
happens correctly.
* Just to remove some redundant code in tn_config.c, a bunch of calls to
generate_sorcery_enum_from_str() and generate_sorcery_enum_to_str() were
replaced with a single call to …
> stir_shaken: Fix propagation of attest_level and a few other values

- cel/cel_custom.c
If a filename starts with a '/' in cel_custom [mappings] assume it is a absolute file path and not relative filename/path to AST_LOG_DIR/cel_custom/
> cel_custom: Allow absolute filenames.

- main/channel.c
When a channel masquerade occurs, the value of CHANNEL(userfield) is not copied to the new ast_channel. A channel masquerade occurs when 2 existing channels are bridged using a simple bridge. Or when a simple bridge is broken and both channels continue independently.
Fixes: #882
> channel: Value CHANNEL(userfield) is lost by BRIDGE_ENTER/BRIDGE_LEAVE.

- main/astfd.c
Don't pass through a NULL argument to fclose, which is undefined behavior, and instead return -1 and set errno appropriately. This avoids a compiler warning with gcc 13.2.0.
Resolves: #900
> astfd.c: Avoid calling fclose with NULL argument.

- res/res_agi.c
res_agi.c:  After the speech recognition module obtains and reads the voice data, it sets fr = NULL.
When using the speech recognition module, occasional crashes occur. The core file indicates that the crash is due to: "double free or corruption (out)". To address this issue, we have modified the code to explicitly set fr = NULL after executing ast_frfree(fr) following the loop that reads the voice data. This modification helps prevent issues related to repeated deallocation under special circumstances.
Resolves:  #772
> res_agi.c: In the speech recognition module, set fr to NULL after ast_frfree(fr).

- res/res_rtp_asterisk.c
In dtls_srtp_handle_timeout(), when DTLSv1_get_timeout() returned
success but with a timeout of 0, we were stopping the timer and
decrementing the refcount on instance but not resetting the
timeout_timer to -1.  When dtls_srtp_stop_timeout_timer()
was later called, it was atempting to stop a stale timer and could
decrement the refcount on instance again which would then cause
the instance destructor to run early.  This would result in either
a FRACK or a SEGV when ast_rtp_stop(0 was called.
According to the OpenSSL docs, we shouldn't have been stopping the
timer when DTLSv1_get_timeout() returned success and the new timeout
was 0 anyway.  We should have been calling DTLSv1_handle_timeout()
again immediately so we now reschedule the timer callback for
1ms (almost immediately). …
> res_rtp_asterisk: Fix dtls timer issues causing FRACKs and SEGVs

- main/asterisk.c
- main/config.c
- main/manager.c
- res/res_timing_kqueue.c
- tests/test_crypto.c
asterisk.c, manager.c: Increase buffer sizes to avoid truncation warnings.
config.c: Include header file for WIFEXITED/WEXITSTATUS macros.
res_timing_kqueue: Use more portable format specifier.
test_crypto: Use non-linux limits.h header file.
Resolves: #916
> main, res, tests: Fix compilation errors on FreeBSD.

- apps/app_voicemail.c
- include/asterisk/app.h
- main/asterisk.c
- res/res_agi.c
Calls to `ast_replace_sigchld()` and `ast_unreplace_sigchld()` must be balanced to ensure that we can capture the exit status of child processes when we need to. This extends to functions that call `ast_replace_sigchld()` and `ast_unreplace_sigchld()` such as `ast_safe_fork()` and `ast_safe_fork_cleanup()`.
The primary change here is ensuring that we do not call `ast_safe_fork_cleanup()` in `res_agi.c` if we have not previously called `ast_safe_fork()`.
Additionally we reinforce some of the documentation and add an assertion to, ideally, catch this sooner were this to happen again.
Fixes #922
> res_agi.c: Ensure SIGCHLD handler functions are properly balanced.

- contrib/ast-db-manage/voicemail/versions/64fae6bbe7fb_drop_redundant_index.py
The `voicemail_messages_dir` index is a left prefix of the table's primary key and therefore unnecessary.
> alembic: Drop redundant voicemail_messages index.

- main/manager.c
This unit test checks that dialplan apps and app data specified
as parameters for the Originate action are allowed with the
permissions the user has.
> manager.c: Add unit test for Originate app and appdata permissions (cert-18.9 & cert-20.7 only)

- configs/samples/geolocation.conf.sample
> geolocation.sample.conf: Fix comment marker at end of file

- include/asterisk/acl.h
- main/acl.c
- main/dnsmgr.c
The dnsmgr_refresh() function checks to see if the IP address associated with a name/service has changed. The gotcha is that the ast_get_ip_or_srv() function only returns the first IP address returned by the DNS query. If there are multiple IPs associated with the name and the returned order is not consistent (e.g. with DNS round-robin) then the other IP addresses are not included in the comparison and the entry is flagged as changed even though the IP is still valid.
Updated the code to check all IP addresses and flag a change only if the original IP is no longer valid.
Resolves #924
> dnsmgr.c: dnsmgr_refresh() incorrectly flags change with DNS round-robin

- main/core_unreal.c
- main/stream.c
When the channel tech is multistream capable, the reference to
chan_topology was passed to the new channel.  When the channel tech
isn't multistream capable, the reference to chan_topology was never
released.  "Local" channels are multistream capable so it didn't
affect them but the confbridge "CBAnn" and the bridge_media
"Recorder" channels are not so they caused a leak every time one
of them was created.
Also added tracing to ast_stream_topology_alloc() and
stream_topology_destroy() to assist with debugging.
Resolves: #938
> core_unreal.c: Fix memory leak in ast_unreal_new_channels() (cert-18.9 only)

- main/core_unreal.c
- main/stream.c
When the channel tech is multistream capable, the reference to
chan_topology was passed to the new channel.  When the channel tech
isn't multistream capable, the reference to chan_topology was never
released.  "Local" channels are multistream capable so it didn't
affect them but the confbridge "CBAnn" and the bridge_media
"Recorder" channels are not so they caused a leak every time one
of them was created.
Also added tracing to ast_stream_topology_alloc() and
stream_topology_destroy() to assist with debugging.
Resolves: #938
> core_unreal.c: Fix memory leak in ast_unreal_new_channels()

- third-party/pjproject/Makefile
- third-party/pjproject/Makefile.rules
- third-party/pjproject/README-hacking.md
* pjproject is now configured with --disable-libsrtp so it will
build correctly when doing "out-of-tree" development.  Asterisk
doesn't use pjproject for handling media so pjproject doesn't
need libsrtp itself.
* The pjsua app (which we used to use for the testsuite) no longer
builds in pjproject's master branch so we just skip it.  The
testsuite no longer needs it anyway.
See third-party/pjproject/README-hacking.md for more info on building
pjproject "out-of-tree".
> pjproject_bundled:  Tweaks to support out-of-tree development

- apps/app_dial.c
If to_answer is -1, simply comparing to see if the progress timeout is smaller than the answer timeout to prefer it will fail. Add an additional check that chooses the progress timeout if there is no answer timeout (or as before, if the progress timeout is smaller).
Resolves: #821
> app_dial: Fix progress timeout calculation with no answer timeout.

- apps/app_mixmonitor.c
Adds the 'D' option to app_mixmonitor that interleaves the input and
output frames of the channel being recorded in the monitor output frame.
This allows for two streams in the recording: the transmitted audio and
the received audio. The 't' and 'r' options are compatible with this.
Fixes: #945
UserNote: The MixMonitor application now has a new 'D' option which
interleaves the recorded audio in the output frames. This allows for
stereo recording output with one channel being the transmitted audio and
the other being the received audio. The 't' and 't' options are
compatible with this.
> app_mixmonitor: Add 'D' option for dual-channel audio.

- res/res_srtp.c
There's really no point in spamming logs with a verbose message
for every unsupported crypto suite an older client may send
in an SDP.  If none are supported, there will be an error or
warning.
> res_srtp: Change Unsupported crypto suite msg from verbose to debug

- apps/app_mixmonitor.c
Adds the 'D' option to app_mixmonitor that interleaves the input and
output frames of the channel being recorded in the monitor output frame.
This allows for two streams in the recording: the transmitted audio and
the received audio. The 't' and 'r' options are compatible with this.
Fixes: #945
UserNote: The MixMonitor application now has a new 'D' option which
interleaves the recorded audio in the output frames. This allows for
stereo recording output with one channel being the transmitted audio and
the other being the received audio. The 't' and 't' options are
compatible with this.
> app_mixmonitor: Add 'D' option for dual-channel audio. (certified/18.9)

- main/config.c
ast_variable_update currently sets the first match for a variable, as opposed to the last one. This issue is complementary to that raised in #244.
This is incorrect and results in the wrong (or no) action being taken in cases where a section inherits from a template section. When the traversal occurs to update the setting, the existing code erroneously would use the first of possibly multiple matches in its update logic, which is wrong. Now, explicitly use the last match in the traversal, which will ensure that the actual setting is updated properly, and not skipped or ignored because a template from which the setting's section inherits was used for comparison.
Resolves: #960
UpgradeNote: Config variables, when set/updated, such as via AMI, will now have the corresponding setting updated, …
> config.c Make ast_variable_update update last match.

- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_transport_events.c
The key used for transport monitors was the remote host name for the
transport and not the remote address resolved for this domain.
This was problematic for domains returning multiple addresses as several
transport monitors were created with the same key.
Whenever a subsystem wanted to register a callback it would always end
up attached to the first transport monitor with a matching key.
The key used for transport monitors is now the remote address and port
the transport actually connected to.
Fixes: #932
> pjsip_transport_events: handle multiple addresses for a domain

- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_configuration.c
The tenantid field was originally added to the ast_sip_endpoint
structure at the end of the AST_DECLARE_STRING_FIELDS block.  This
caused everything after it in the structure to move down in memory
and break ABI compatibility.  It's now at the end of the structure
as an AST_STRING_FIELD_EXTENDED.  Given the number of string fields
in the structure now, the initial string field allocation was
also increased from 64 to 128 bytes.
Resolves: #982
> res_pjsip: Move tenantid to end of ast_sip_endpoint

- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_configuration.c
The tenantid field was originally added to the ast_sip_endpoint
structure at the end of the AST_DECLARE_STRING_FIELDS block.  This
caused everything after it in the structure to move down in memory
and break ABI compatibility.  It's now at the end of the structure
as an AST_STRING_FIELD_EXTENDED.  Given the number of string fields
in the structure now, the initial string field allocation was
also increased from 64 to 128 bytes.
Resolves: #982
> res_pjsip: Move tenantid to end of ast_sip_endpoint (cert-18.9 only)

- funcs/func_pjsip_aor.c
- funcs/func_pjsip_contact.c
Clarified the use of the contact ID returned from PJSIP_AOR.
Resolves: #990
> func_pjsip_aor/contact: Fix documentation for contact ID

- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/4f91fc18c979_add_suppress_moh_on_sendonly.py
- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip_sdp_rtp.c
Normally, when one party in a call sends Asterisk an SDP with
a "sendonly" or "inactive" attribute it means "hold" and causes
Asterisk to start playing MOH back to the other party. This can be
problematic if it happens at certain times, such as in a 183
Progress message, because the MOH will replace any early media you
may be playing to the calling party. If you set this option
to "yes" on an endpoint and the endpoint receives an SDP
with "sendonly" or "inactive", Asterisk will NOT play MOH back to
the other party.
Resolves: https://github.com/asterisk/asterisk/issues/979
UserNote: The new "suppress_moh_on_sendonly" endpoint option
can be used to prevent playing MOH back to a caller if the remote
end sends "sendonly" or "inactive" (hold) to Asterisk in an SDP.
> res_pjsip: Add new endpoint option "suppress_moh_on_sendonly" (cert-18.9 only)

- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/4f91fc18c979_add_suppress_moh_on_sendonly.py
- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip_sdp_rtp.c
Normally, when one party in a call sends Asterisk an SDP with
a "sendonly" or "inactive" attribute it means "hold" and causes
Asterisk to start playing MOH back to the other party. This can be
problematic if it happens at certain times, such as in a 183
Progress message, because the MOH will replace any early media you
may be playing to the calling party. If you set this option
to "yes" on an endpoint and the endpoint receives an SDP
with "sendonly" or "inactive", Asterisk will NOT play MOH back to
the other party.
Resolves: #979
UserNote: The new "suppress_moh_on_sendonly" endpoint option
can be used to prevent playing MOH back to a caller if the remote
end sends "sendonly" or "inactive" (hold) to Asterisk in an SDP.
> res_pjsip: Add new endpoint option "suppress_moh_on_sendonly"

- contrib/ast-db-manage/README.md
- contrib/ast-db-manage/config/versions/4f91fc18c979_add_suppress_moh_on_sendonly.py
- res/res_pjsip/pjsip_configuration.c
The suppress_moh_on_sendonly endpoint option should have been
defined as OPT_BOOL_T in pjsip_configuration.c and AST_BOOL_VALUES
in the alembic script instead of OPT_YESNO_T and YESNO_VALUES.
Also updated contrib/ast-db-manage/README.md to indicate that
AST_BOOL_VALUES should always be used and provided an example.
Resolves: #995
> res_pjsip: Change suppress_moh_on_sendonly to OPT_BOOL_T

- configs/samples/stir_shaken.conf.sample
- res/res_stir_shaken/attestation_config.c
- res/res_stir_shaken/common_config.h
- res/res_stir_shaken/crypto_utils.c
- res/res_stir_shaken/profile_config.c
- res/res_stir_shaken/stir_shaken_doc.xml
- res/res_stir_shaken/tn_config.c
- res/res_stir_shaken/verification_config.c
Added a new option "unknown_tn_attest_level" to allow Identity
headers to be sent when a callerid TN isn't explicitly configured
in stir_shaken.conf.  Since there's no TN object, a private_key_file
and public_cert_url must be configured in the attestation or profile
objects.
Since "unknown_tn_attest_level" uses the same enum as attest_level,
some of the sorcery macros had to be refactored to allow sharing
the enum and to/from string conversion functions.
Also fixed a memory leak in crypto_utils:pem_file_cb().
Resolves: #921
UserNote: You can now set the "unknown_tn_attest_level" option
in the attestation and/or profile objects in stir_shaken.conf to
enable sending Identity headers for callerid TNs not explicitly
configured.
> res_stir_shaken: Allow sending Identity headers for unknown TNs

- funcs/func_curl.c
This patch adds additional curl TLS options / options to support mTLS 
authenticated requests:
* ssl_verifyhost - perform a host verification on the peer certificate
(CURLOPT_SSL_VERIFYHOST).
* ssl_cainfo - define a CA certificate file (CURLOPT_CAINFO),
* ssl_capath - define a CA certificate directory (CURLOPT_CAPATH),
* ssl_cert - define a client certificate for the request 
(CURLOPT_SSLCERT),
* ssl_certtype - specify the client certificate type 
(CURLOPT_SSLCERTTYPE),
* ssl_key - define a client private key for the request
(CURLOPT_SSLKEY),
* ssl_keytype - specify the client private key type 
(CURLOPT_SSLKEYTYPE),
* ssl_keypasswd - set a password for the private key, if required 
(CURLOPT_KEYPASSWD),
UserNote: The following new configuration options are now available 
in the …
> func_curl.c: Add additional CURL options for SSL requests

- main/manager.c
This update adds the processed call count to the CoreStatus AMI Action responsie. This output is similar to the values returned by "core show channels" or "core show calls" in the CLI.
UserNote: The current processed call count is now returned as CoreProcessedCalls from the CoreStatus AMI Action.
> manager.c: Add Processed Call Count to CoreStatus output

- res/res_rtp_asterisk.c
res_rtp_asterisk.c: Fix bridged_payload matching with sample rate for DTMF
Fixes #1004
> Fix bridged_payload matching with sample rate for DTMF

- res/res_rtp_asterisk.c
We faced with no audio issue when media source changed during the call (e.g. call transfer, audio prompt and then some sip endpoint, etc.). Issue related to big timestamp skew. Solution here is to set Mark when we detect such case.
Fixes: #927
> res_rtp_asterisk.c: Set mark on rtp when timestamp skew is too big

- configs/samples/res_curl.conf.sample
This update properly documents all the current configuration options supported by the curl implementation, including the new ssl_* options.
> res_curl.conf.sample: clean up sample configuration and add new SSL options.

- channels/chan_pjsip.c
Currently, when a chan_pjsip channel receives a VIDUPDATE indication, an RTP VIDUPDATE frame is only queued on a H.264 stream if WebRTC is enabled on that endpoint. This restriction does not really make sense.
Now, a VIDUPDATE RTP frame is written even if WebRTC is not enabled (as is the case for VP8, VP9, and H.265 streams).
Resolves: #1013
> chan_pjsip: Send VIDUPDATE RTP frame for all H.264 streams

- channels/chan_iax2.c
Add a log message for a path that currently silently drops IAX2 frames without indicating that anything is wrong.
> chan_iax2: Add log message for rejected calls.

- funcs/func_uuid.c
This function is useful for uniquely identifying calls, recordings, and other entities in distributed environments, as well as for generating an argument for the AudioSocket application.
> func_uuid: Add a new dialplan function to generate UUIDs

- formats/format_gsm.c
Because URL parser does not work properly and has been removed(https://github.com/asterisk/asterisk/commit/6428124b06bc0147ce6c6379a96da4c8ac559af7), i added mime type to format_gsm to parse file extensions from content-type:
```
Connected to Asterisk 20.11.0 currently running on asterisk20 (pid = 3316)
asterisk20*CLI> media cache show http://asterisk.khabulyak.su/gsm/your
URI: http://asterisk.khabulyak.su/gsm/your
----------------------------------------
Path: /var/cache/asterisk/bucket-TjDHtf.gsm
etag: "674dc5f6-420"
last-modified: Mon, 02 Dec 2024 14:36:38 GMT
ext: .gsm
content-type: audio/x-gsm
__actual_expires:                     1733152296
```
Without this change asterisk can't determine file extension in this case and can't play a file.
```
-- Executing [123@main:1] …
```
> format_gsm.c: Added mime type

- main/config.c
ast_variable_retrieve currently returns the first match for a variable, as opposed to the last one. This is problematic because modules that load config settings by explicitly calling ast_variable_retrieve on a variable name (as opposed to iterating through all the directives as specified) will end up taking the first specified value, such as the default value from the template rather than the actual effective value in an individual config section, leading to the wrong config.
This fixes this by making ast_variable_retrieve return the last match, or the most recently overridden one, as the effective setting. This is similar to what the -1 index in the AST_CONFIG function does.
There is another function, ast_variable_find_last_in_list, that does something similar. However, it's a slightly …
> config.c: Make ast_variable_retrieve return last match.

- main/Makefile
Although C++ files (as extension .cc) have been handled in the module
directories for many years, the main directory was missing one line in its
Makefile that prevented C++ files from being recognised there.
> Allow C++ source files (as extension .cc) in the main directory

- apps/app_queue.c
app_queue: indicate the paused state of a dynamically added member in queue_log.
Fixes: #1021
> app_queue: indicate the paused state in queue_log (ADDMEMBER event)

- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/44bd6dd914fa_add_qualify_2xx_only_option.py
- include/asterisk/res_pjsip.h
- res/res_pjsip/location.c
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_options.c
- res/res_pjsip_registrar.c
Added a new option "qualify_2xx_only" to the res_pjsip AOR qualify
feature to mark a contact as available only if an OPTIONS request
returns a 2XX response. If the option is not specified or is false,
any response to the OPTIONS request marks the contact as available.
UserNote: The pjsip.conf AOR section now has a "qualify_2xx_only"
option that can be set so that only 2XX responses to OPTIONS requests
used to qualify a contact will mark the contact as available.
> res_pjsip: Add new AOR option "qualify_2xx_only"

- include/asterisk/test.h
- main/test.c
- tests/test_skel.c
Unit tests can now be passed custom arguments from the command
line.  For example, the following command would run the "mytest" test
in the "/main/mycat" category with the option "myoption=54"
`CLI> test execute category /main/mycat name mytest options myoption=54`
You can also pass options to an entire category...
`CLI> test execute category /main/mycat options myoption=54`
Basically, everything after the "options" keyword is passed verbatim to
the test which must decide what to do with it.
* A new API ast_test_get_cli_args() was created to give the tests access to
the cli_args->argc and cli_args->argv elements.
* Although not needed for the option processing, a new macro
ast_test_validate_cleanup_custom() was added to test.h that allows you
to specify a custom error message instead of …
> Add ability to pass arguments to unit tests from the CLI

- include/asterisk/astmm.h
- include/asterisk/lock.h
- include/asterisk/logger.h
- include/asterisk/strings.h
A few tweaks needed to be done to some existing header files to allow them to
be compiled when included from C++ source files.
logger.h had declarations for ast_register_verbose() and
ast_unregister_verbose() which caused C++ issues but those functions were
actually removed from logger.c many years ago so the declarations were just
removed from logger.h.
> Header fixes for compiling C++ source files

- tests/test_message.c
* test_message.c: Fix segfaults caused by passing NULL as an sprintf fmt.
> gcc14: Fix issues caught by gcc 14

- channels/sip/reqresp_parser.c
- tests/test_message.c
* reqresp_parser.c: Fix misuse of "static" with linked list definitions
* test_message.c: Fix segfaults caused by passing NULL as an sprintf fmt
> gcc14: Fix issues caught by gcc 14 (branches <= 20)

- channels/chan_dahdi.c
- include/asterisk/channelstate.h
- main/devicestate.c
Previously, when AST_CONTROL_RINGING was received by
a DAHDI device, it would set its channel state to
AST_STATE_RINGING. However, an analysis of the codebase
and other channel drivers reveals RINGING corresponds to
physical power ringing, whereas AST_STATE_RING should be
used for audible ringback on the channel. This also ensures
the correct device state is returned by the channel state
to device state conversion.
Since there seems to be confusion in various places regarding
AST_STATE_RING vs. AST_STATE_RINGING, some documentation has
been added or corrected to clarify the actual purposes of these
two channel states, and the associated device state mapping.
An edge case that prompted this fix, but isn't explicitly
addressed here, is that of an incoming call to an FXO port.
The channel …
> chan_dahdi: Fix wrong channel state when RINGING recieved.

- main/config.c
This was identified and fixed by @Allan-N in #918 but it is an important fix in its own right.
The fix here is slightly different than Allan's in that we just move the initialization of the problematic AO2 container to where it is first used.
Fixes #1046
> config.c: Fix off-nominal reference leak.

- main/config.c
Configurations loaded with the ast_config_load2() API and later written out with ast_config_text_file_save2() will have any leading whitespace stripped away.  The APIs should make reasonable efforts to maintain the content and formatting of the configuration files.
This change retains any leading whitespace from comment lines that start with a ";".
Resolves: https://github.com/asterisk/asterisk/issues/970
> config.c: retain leading whitespace before comments

- configs/samples/pjsip.conf.sample
- configure
- configure.ac
- contrib/ast-db-manage/config/versions/abdc9ede147d_add_fields_to_ps_auths_to_support_new_.py
- include/asterisk/autoconfig.h.in
- include/asterisk/res_pjsip.h
- res/res_pjproject.c
- res/res_pjsip/config_auth.c
- res/res_pjsip/config_global.c
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_distributor.c
- res/res_pjsip_authenticator_digest.c
- res/res_pjsip_outbound_authenticator_digest.c
- third-party/pjproject/configure.m4
- third-party/pjproject/patches/config_site.h
* Refactored pjproject code to support the new algorithms and
added a patch file to third-party/pjproject/patches
* Added new parameters to the pjsip auth object:
* password_digest = `<algorithm>:<digest>`
* supported_algorithms_uac = List of algorithms to support
when acting as a UAC.
* supported_algorithms_uas = List of algorithms to support
when acting as a UAS.
See the auth object in pjsip.conf.sample for detailed info.
* Updated both res_pjsip_authenticator_digest.c (for UAS) and
res_pjsip_outbound_authentocator_digest.c (UAC) to suport the
new algorithms.
The new algorithms are only available with the bundled version
of pjproject, or an external version > 2.14.1.  OpenSSL version
1.1.1 or greater is required to support SHA-512-256.
Resolves: #948
UserNote: The SHA-256 and …
> Add SHA-256 and SHA-512-256 as authentication digest algorithms

- configs/samples/res_pgsql.conf.sample
- res/res_config_pgsql.c
The syntax will match the other modules cel and cdr.
Let me know if this is the correct way to correct syntaxes.
Also i noticed that this module is the only one that use socket as option.
> res_config_pgsql: normalize database connection options

- main/logger.c
this typo was mentioned before, but never got fixed.  https://community.asterisk.org/t/logger-cannot-log-long-json-lines-properly/87618/6
(I found it elsewhere too but wasn't able to dig it up)
We are hunting down an issue where the logger fails to log our Error (probably caused by invalid chars in the caller-ID).
> logger.c fix: malformed JSON template

- configs/samples/cdr_pgsql.conf.sample
- configs/samples/cel_pgsql.conf.sample
These files were using postgres instead of asterisk.
> samples: Use "asterisk" instead of "postgres" for username

- doc/appdocsxml.dtd
- include/asterisk/agi.h
- include/asterisk/manager.h
- include/asterisk/pbx.h
- include/asterisk/xmldoc.h
- main/config_options.c
- main/manager.c
- main/pbx_app.c
- main/pbx_functions.c
- main/xmldoc.c
- res/res_agi.c
- rest-api-templates/api.wiki.mustache
- rest-api-templates/swagger_model.py
* Added the "since" element to the XML configObject and configOption elements in appdocsxml.dtd.
* Added the "Since" section to the following CLI output:
```
config show help <module> <object>
config show help <module> <object> <option>
core show application <app>
core show function <func>
manager show command <command>
manager show event <event>
agi show commands topic <topic>
```
* Refactored the commands above to output their sections in the same order:
Synopsis, Since, Description, Syntax, Arguments, SeeAlso
* Refactored the commands above so they all use the same pattern for writing the output to the CLI.
* Fixed several memory leaks caused by failure to free temporary output buffers.
* Added a "since" array to the mustache template for the top-level resources (Channel, Endpoint, …
> docs: Enable since/version handling for XML, CLI and ARI documentation

- channels/pjsip/dialplan_functions_doc.xml
- main/bucket.c
- main/named_acl.c
- res/res_geolocation/geoloc_doc.xml
- res/res_http_media_cache.c
* channels/pjsip/dialplan_functions_doc.xml: Added xmlns:xi to docs element.
* main/bucket.c: Removed XML completely since the "bucket" and "file" objects
are internal only with no config file.
* main/named_acl.c: Fixed the configFile element name. It was "named_acl.conf"
and should have been "acl.conf"
* res/res_geolocation/geoloc_doc.xml: Added xmlns:xi to docs element.
* res/res_http_media_cache.c: Fixed the configFile element name. It was
"http_media_cache.conf" and should have been "res_http_media_cache.conf".
> docs: Various XML fixes

- channels/chan_dahdi.c
- channels/chan_dahdi.h
- channels/sig_analog.c
- channels/sig_analog.h
- configs/samples/chan_dahdi.conf.sample
This adds the Last Number Redial feature to
simple switch.
UserNote: Users can now redial the last number
called if the lastnumredial setting is set to yes.
Resolves: #437
> sig_analog: Add Last Number Redial feature.

- contrib/scripts/ast_tls_cert
Currently, ast_tls_cert file is hardcoded to use the -des3 option for 3DES encryption, and the script needs to be manually modified to not require a passphrase. Add an option (-e) that disables encryption of the CA private key so no passphrase is required.
Resolves: #1064
> ast_tls_cert: Add option to skip passphrase for CA private key.

- include/asterisk/res_pjsip.h
- res/res_pjsip/config_auth.c
- res/res_pjsip/config_global.c
- res/res_pjsip/pjsip_distributor.c
An issue in config_auth.c:ast_sip_auth_digest_algorithms_vector_init() was
causing double allocations for the two supported_algorithms vectors to the
tune of 915 bytes.  The leak only happens on startup and when a reload is done
and doesn't get bigger with the number of auth objects defined.
* Pre-initialized the two vectors in config_auth:auth_alloc().
* Removed the allocations in ast_sip_auth_digest_algorithms_vector_init().
* Added a note to the doc for ast_sip_auth_digest_algorithms_vector_init()
noting that the vector passed in should be initialized and empty.
* Simplified the create_artificial_auth() function in pjsip_distributor.
* Set the vector initialization count to 0 in config_global:global_apply().
> res_pjsip: Fix startup/reload memory leak in config_auth.

- contrib/ast-db-manage/config/versions/44bd6dd914fa_add_qualify_2xx_only_option.py
- contrib/ast-db-manage/config/versions/abdc9ede147d_add_fields_to_ps_auths_to_support_new_.py
This commit doesn't actually change anything.  It just adds the following
upgrade notes that were omitted from the original commits.
Resolves: #1097
UpgradeNote: Two commits in this release...
'Add SHA-256 and SHA-512-256 as authentication digest algorithms'
'res_pjsip: Add new AOR option "qualify_2xx_only"'
...have modified alembic scripts for the following database tables: ps_aors,
ps_contacts, ps_auths, ps_globals. If you don't use the scripts to update
your database, reads from those tables will succeeed but inserts into the
ps_contacts table by res_pjsip_registrar will fail.
> alembic: Database updates required.

- configs/samples/rtp.conf.sample
> rtp.conf.sample: Correct stunaddr example.

- apps/app_mixmonitor.c
The `Options` argument was erroneously documented as lowercase `options`.
> docs: Fix minor typo in MixMonitor AMI action

- res/res_agi.c
This process was a bit different than the others because everything
is in the same file, there's an array that contains the command
names and their handler functions, and the last command was created
over 15 years ago.
* Dump a `git blame` of res/res_agi.c from BEFORE the handle_* prototypes
were changed.
* Create a command <> handler function xref by parsing the the agi_command
array.
* For each entry, grep the function definition line "static int handle_*"
from the git blame output and capture the commit.  This will be the
commit the command was created in.
* Do a `git tag --contains <commit> | sort -V | head -1` to get the
tag the function was created in.
* Add a single since/version element to the command XML.  Multiple versions
aren't supported here because the branching and tagging …
> docs: Add version information to AGI command XML elements.

- funcs/func_strings.c
When in single-argument mode (very rarely used), a malformation of a column
name (also very rare) could cause a NULL to be returned when retrieving the
channel variable for that column.  Passing that to strncat causes a SEGV.  We
now check for the NULL and print a warning message.
Resolves: #1101
> func_strings.c: Prevent SEGV in HASH single-argument mode.

- include/asterisk/channel.h
- main/channel.c
Nothing ever sets the `AST_GENERATOR_FD`, so this block of code will never execute. It also is the only place where the `generate` callback is called with the channel lock held which made it difficult to reason about the thread safety of `ast_generator`s.
In passing, also note that `AST_AGENT_FD` isn't used either.
> channel.c: Remove dead AST_GENERATOR_FD code.

- channels/chan_pjsip.c
- channels/pjsip/dialplan_functions.c
- channels/pjsip/dialplan_functions_doc.xml
- channels/pjsip/include/dialplan_functions.h
- include/asterisk/frame.h
- include/asterisk/refer.h
- include/asterisk/res_pjsip_session.h
- include/asterisk/stasis_channels.h
- main/refer.c
- main/stasis_channels.c
- res/ari/ari_model_validators.c
- res/ari/ari_model_validators.h
- res/ari/resource_channels.c
- res/ari/resource_channels.h
- res/res_ari_channels.c
- res/res_pjsip_refer.c
- rest-api/api-docs/channels.json
- rest-api/api-docs/events.json
Introduce an ARI ChannelTransfer event and implement transfer_progress to propagate progress back to asterisk.
Introduce a dialplan function and channel variable in pjsip to allow generating the ChannelTransfer event and generate a SIP NOTIFY based on the transfer progress.
> ARI/pjsip: Make it possible to control transfers through ARI (master,22 only)

- channels/chan_pjsip.c
- channels/pjsip/dialplan_functions.c
- channels/pjsip/dialplan_functions_doc.xml
- channels/pjsip/include/dialplan_functions.h
- include/asterisk/frame.h
- include/asterisk/refer.h
- include/asterisk/res_pjsip_session.h
- include/asterisk/stasis_channels.h
- main/refer.c
- main/stasis_channels.c
- res/ari/ari_model_validators.c
- res/ari/ari_model_validators.h
- res/ari/resource_channels.c
- res/ari/resource_channels.h
- res/res_ari_channels.c
- res/res_pjsip_refer.c
- rest-api/api-docs/channels.json
- rest-api/api-docs/events.json
Introduce a ChannelTransfer event and the ability to notify progress to ARI. Implement emitting this event from the PJSIP channel instead of handling the transfer in Asterisk when configured.
Introduce a dialplan function to the PJSIP channel to switch between the "core" and "ari-only" behavior.
UserNote: Call transfers on the PJSIP channel can now be controlled by ARI. This can be enabled by using the PJSIP_TRANSFER_HANDLING(ari-only) dialplan function.
> ARI/pjsip: Make it possible to control transfers through ARI (21,20 only)

- include/asterisk/res_stir_shaken.h
- res/res_pjsip_stir_shaken.c
- res/res_stir_shaken/verification.c
The verification check for missing or anonymous callerid was happening before
the endpoint's profile was retrieved which meant that the failure_action
parameter wasn't available.  Therefore, if verification was enabled and there
was no callerid or it was "anonymous", the call was immediately terminated
instead of giving the dialplan the ability to decide what to do with the call.
* The callerid check now happens after the verification context is created and
the endpoint's stir_shaken_profile is available.
* The check now processes the callerid failure just as it does for other
verification failures and respects the failure_action parameter.  If set
to "continue" or "continue_return_reason", `STIR_SHAKEN(0,verify_result)`
in the dialplan will return "invalid_or_no_callerid".
* If the …
> res_stir_shaken: Allow missing or anonymous CID to continue to the dialplan.

- res/res_config_pgsql.c
A recent commit accidentally removed the code that sets dbname.
This commit adds it back in.
Resolves: #1119
> res_config_pgsql: Fix regression that removed dbname config.

- main/bridge_channel.c
Due to a potential race condition via ARI when hanging up a channel hangup with cause
while also deleting a bridge containing that channel, the bridge delete can over-write
the hangup cause code resulting in Normal Call Clearing instead of the set value.
With this change, bridge deletion will only set the hangup code if it hasn't been
previously set.
Resolves: #1124
> bridge_channel: don't set cause code on channel during bridge delete if already set

- include/asterisk/bridge.h
- include/asterisk/stasis_bridges.h
- main/bridge.c
- main/stasis_bridges.c
- res/ari/resource_bridges.c
- res/ari/resource_bridges.h
- res/res_ari_bridges.c
- res/res_stasis.c
- res/stasis/stasis_bridge.c
- rest-api/api-docs/bridges.json
Issues:
* The bridging core allowed multiple bridges to be created with the same
unique bridgeId at the same time.  Only the last bridge created with the
duplicate name was actually saved to the core bridges container.
* The bridging core was creating a stasis topic for the bridge and saving it
in the bridge->topic field but not increasing its reference count.  In the
case where two bridges were created with the same uniqueid (which is also
the topic name), the second bridge would get the _existing_ topic the first
bridge created.  When the first bridge was destroyed, it would take the
topic with it so when the second bridge attempted to publish a message to
it it either FRACKed or SEGVd.
* The bridge destructor, which also destroys the bridge topic, is run from the
bridge manager thread …
> bridging: Fix multiple bridging issues causing SEGVs and FRACKs.

- channels/chan_dahdi.c
- channels/chan_iax2.c
- channels/chan_motif.c
- channels/chan_unistim.c
- channels/console_gui.c
- channels/console_video.c
- channels/iax2/include/astobj.h
- channels/iax2/include/firmware.h
- channels/iax2/include/parser.h
- channels/iax2/include/provision.h
- channels/pjsip/dialplan_functions_doc.xml
- channels/sig_analog.c
- channels/sig_pri.c
- channels/sig_pri.h
- channels/sig_ss7.h
- channels/vcodecs.c
Found via `codespell -q 3 -S "./CREDITS,*.po" -L abd,asent,atleast,cachable,childrens,contentn,crypted,dne,durationm,enew,exten,inout,leapyear,mye,nd,oclock,offsetp,ot,parm,parms,preceeding,pris,ptd,requestor,re-use,re-used,re-uses,ser,siz,slanguage,slin,thirdparty,varn,varns,ues`
> docs: Fix various typos in channels/

- res/res_rtp_asterisk.c
> res_rtp_asterisk.c: Use correct timeout value for T.140 RED timer.

- res/res_rtp_asterisk.c
This reverts commit f30ad96b3f467739c38ff415e80bffc4afff1da7.
The original change was not RFC compliant and caused issues because it set the RTP marker bit in cases when it shouldn't be set. See the linked issue #1135 for a detailed explanation.
Fixes: #1135.
> Revert "res_rtp_asterisk.c: Set Mark on rtp when timestamp skew is too big"

- rest-api-templates/swagger_model.py
Recent python versions complain when backslashes in strings create invalid
escape sequences.  This causes issues for strings used as regex patterns like
`'^List\[(.*)\]$'` where you want the regex parser to treat `[` and `]`
as literals.  Double-backslashing is one way to fix it but simply converting
the string to a raw string `re.match(r'^List\[(.*)\]$', text)` is easier
and less error prone.
> swagger_model.py: Fix invalid escape sequence in get_list_parameter_type().

- apps/app_agent_pool.c
- main/stasis_bridges.c
- main/stasis_channels.c
- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip/pjsip_manager.xml
- res/res_pjsip_outbound_registration.c
- res/res_pjsip_pubsub.c
- res/res_pjsip_registrar.c
Most of this patch is adding missing PJSIP-related event
documentation, but the one functional change was adding a sorcery
to-string handler for endpoint's `redirect_method` which was not
showing up in the AMI event details or `pjsip show endpoint
<endpoint>` output.
The rest of the changes are summarized below:
* app_agent_pool.c: Typo fix Epoche -> Epoch.
* stasis_bridges.c: Add missing AttendedTransfer properties.
* stasis_channels.c: Add missing AgentLogoff properties.
* pjsip_manager.xml:
- Add missing AorList properties.
- Add missing AorDetail properties.
- Add missing ContactList properties.
- Add missing ContactStatusDetail properties.
- Add missing EventDetail properties.
- Add missing AuthList properties.
- Add missing AuthDetail properties.
- Add missing TransportDetail …
> docs: AMI documentation fixes.

- res/res_pjsip/config_transport.c
Resolves an issue where the tcp_keepalive_enable option was not properly enabled in the sample configuration due to an incorrect default flag setting.
Fixes: #1149
> fix: Correct default flag for tcp_keepalive_enable option

- res/res_rtp_asterisk.c
RFC 8839[1] indicates that the `ice-ufrag` and `ice-pwd` attributes can be up to 256 bytes long. While we don't generate values of that size, we should be able to accomodate them without truncating.
1. https://www.rfc-editor.org/rfc/rfc8839#name-ice-ufrag-and-ice-pwd-attri
> res_rtp_asterisk.c: Don't truncate spec-compliant `ice-ufrag` or `ice-pwd`.

- res/res_pjsip_outbound_registration.c
Commit e86f937e added AMI documentation to the module but the cherry-pick
from master to the 20 branch pulled in an xpointer reference to the
`user_agent` config option which doesn't actually exist in 20.  This causes
asterisk to fail to start because it can't load the core-en_US.xml
documentation file.  The CI cherry-pick tests should have caught this but
there was bug in the cherry-picker that was causing the commits to be
cherry-picked to the wrong branch.  Just removing the xpointer reference
resolves the issue.
> res_pjsip_outbound_registration.c: Remove xpointer reference to user_agent.

- apps/app_stack.c
- doc/appdocsxml.dtd
- main/pbx_builtins.c
Gosub and Goto were not displaying their syntax correctly on the docs
site. This change adds a new way to specify an optional context, an
optional extension, and a required priority that the xml stylesheet can
parse without having to know which optional parameters come in which
order. In Asterisk, it looks like this:
parameter name="context" documentationtype="dialplan_context"
parameter name="extension" documentationtype="dialplan_extension"
parameter name="priority" documentationtype="dialplan_priority" required="true"
The stylesheet will ignore the context and extension parameters, but for
priority, it will automatically inject the following:
[[context,]extension,]priority
This is the correct oder for applications such as Gosub and Goto.
> documentation: Update Gosub, Goto, and add new documentationtype.

- apps/app_stack.c
- doc/appdocsxml.dtd
- main/pbx_builtins.c
Gosub and Goto were not displaying their syntax correctly on the docs
site. This change adds a new way to specify an optional context, an
optional extension, and a required priority that the xml stylesheet can
parse without having to know which optional parameters come in which
order. In Asterisk, it looks like this:
parameter name="context" documentationtype="dialplan_context"
parameter name="extension" documentationtype="dialplan_extension"
parameter name="priority" documentationtype="dialplan_priority" required="true"
The stylesheet will ignore the context and extension parameters, but for
priority, it will automatically inject the following:
[[context,]extension,]priority
This is the correct oder for applications such as Gosub and Goto.
> [certified] documentation: Update Gosub, Goto, and add new documentationtype.

- channels/chan_pjsip.c
- res/res_pjsip/pjsip_config.xml
1. When one channel is placed on hold, the device state is set to ONHOLD
without checking other channels states.
In case of AST_CONTROL_HOLD set the device state as AST_DEVICE_UNKNOWN
to calculate aggregate device state of all active channels.
2. The current implementation incorrectly classifies channels in use.
The only channels that has the states: UP, RING and BUSY are considered as "in use".
A channel should be considered "in use" if its state is anything other than
DOWN or RESERVED.
3. Currently, if the number of channels "in use" is greater than device_state_busy_at,
the system does not set the state to BUSY. Instead, it incorrectly assigns an aggregate
device state.
The endpoint device state should be BUSY if the number of channels "in use" is greater
than or equal to …
> chan_pjsip: set correct Endpoint Device State on multiple channels

- res/res_pjsip/location.c
CLI 'pjsip show contact' does not show enough information.
One must telnet to AMI or write a script to ask Asterisk for example what the User-Agent is on a Contact
This feature adds the same details as PJSIPShowContacts to the CLI
Resolves: #643
> chan_pjsip:  Add the same details as PJSIPShowContacts to the CLI via 'pjsip show contact'

- res/ari/ari_websockets.c
ari_ws_session_registry_dtor() wasn't checking that the container was valid
before running ao2_callback on it to shutdown registered sessions.
> ari_websockets: Fix frack if ARI config fails to load.

- configs/samples/cli.conf.sample
- main/asterisk.c
Commands in the "[startup_commands]" section of cli.conf have historically run
after all core and module initialization has been completed and just before
"Asterisk Ready" is printed on the console. This meant that if you
wanted to debug initialization of a specific module, your only option
was to turn on debug for everything by setting "debug" in asterisk.conf.
This commit introduces options to allow you to run CLI commands earlier in
the asterisk startup process.
A command with a value of "pre-init" will run just after logger initialization
but before most core, and all module, initialization.
A command with a value of "pre-module" will run just after all core
initialization but before all module initialization.
A command with a value of "fully-booted" (or "yes" for backwards …
> asterisk.c: Add "pre-init" and "pre-module" capability to cli.conf. (20 only)

- configs/samples/cli.conf.sample
- main/asterisk.c
Commands in the "[startup_commands]" section of cli.conf have historically run
after all core and module initialization has been completed and just before
"Asterisk Ready" is printed on the console. This meant that if you
wanted to debug initialization of a specific module, your only option
was to turn on debug for everything by setting "debug" in asterisk.conf.
This commit introduces options to allow you to run CLI commands earlier in
the asterisk startup process.
A command with a value of "pre-init" will run just after logger initialization
but before most core, and all module, initialization.
A command with a value of "pre-module" will run just after all core
initialization but before all module initialization.
A command with a value of "fully-booted" (or "yes" for backwards …
> asterisk.c: Add "pre-init" and "pre-module" capability to cli.conf.

- apps/app_queue.c
- configs/samples/queues.conf.sample
Add log-caller-id-name option to log Caller ID Name in queue log
This patch introduces a new global configuration option, log-caller-id-name,
to queues.conf to control whether the Caller ID name is logged when a call enters a queue.
When log-caller-id-name=yes, the Caller ID name is logged
as parameter 4 in the queue log, provided it’s allowed by the
existing log_restricted_caller_id rules. If log-caller-id-name=no (the default),
the Caller ID name is omitted from the logs.
Fixes: #1091
UserNote: This patch adds a global configuration option, log-caller-id-name, to queues.conf
to control whether the Caller ID name is logged as parameter 4 when a call enters a queue.
When log-caller-id-name=yes, the Caller ID name is included in the queue log,
Any '|' characters in the caller ID name will …
> Add log-caller-id-name option to log Caller ID Name in queue log

- main/manager.c
Under certain circumstances the context/extens/prio are stored in the
after_bridge_goto_info. This info is used when the bridge is broken by
for hangup of the other party. In the situation that the bridge is
broken by an AMI Redirect this info is not used but also not removed.
With the result that when the channel is put back in a bridge and the
bridge is broken the execution continues at the wrong
context/extens/prio.
Resolves: #1144
> action_redirect: remove after_bridge_goto_info

- contrib/systemd/asterisk-malloc-trim.service
- contrib/systemd/asterisk-malloc-trim.timer
Adds two files to the contrib/systemd/ directory that can be installed
to periodically run "malloc trim" on Asterisk. These files do nothing
unless they are explicitly moved to the correct location on the system.
Users who are experiencing Asterisk memory issues can use this service
to potentially help combat the problem. These files can also be
configured to change the start time and interval. See systemd.timer(5)
and systemd.time(7) for more information.
UserNote: Service and timer files for systemd have been added to the
contrib/systemd/ directory. If you are experiencing memory issues,
install these files to have "malloc trim" periodically run on the
system.
> contrib: Add systemd service and timer files for malloc trim.

- include/asterisk/http.h
- include/asterisk/http_websocket.h
- include/asterisk/md5.h
- include/asterisk/stasis_app.h
- include/asterisk/tcptls.h
- main/http.c
- main/md5.c
- main/tcptls.c
- res/res_http_websocket.c
- res/res_stasis.c
- res/res_stasis_device_state.c
- res/stasis/control.c
stasis:
* Added stasis_app_is_registered().
* Added stasis_app_control_mark_failed().
* Added stasis_app_control_is_failed().
* Fixed res_stasis_device_state so unsubscribe all works properly.
* Modified stasis_app_unregister() to unsubscribe from all event sources.
* Modified stasis_app_exec to return -1 if stasis_app_control_is_failed()
returns true.
http:
* Added ast_http_create_basic_auth_header().
md5:
* Added define for MD5_DIGEST_LENGTH.
tcptls:
* Added flag to ast_tcptls_session_args to suppress connection log messages
to give callers more control over logging.
http_websocket:
* Add flag to ast_websocket_client_options to suppress connection log messages
to give callers more control over logging.
* Added username and password to ast_websocket_client_options to support
outbound …
> Prequisites for ARI Outbound Websockets

- configure
- configure.ac
- include/asterisk/autoconfig.h.in
- res/res_pjproject.c
Certain platforms (mainly BSD derivatives) have an additional length field in `sockaddr_in6` and `sockaddr_in`.
`ast_sockaddr_from_pj_sockaddr()` does not take this field into account when copying over values from the `pj_sockaddr` into the `ast_sockaddr`. The resulting `ast_sockaddr` will have an uninitialized value for `sin6_len`/`sin_len` while the other `ast_sockaddr` (not converted from a `pj_sockaddr`) to check against in `ast_sockaddr_pj_sockaddr_cmp()` has the correct length value set.
This has the effect that `ast_sockaddr_cmp()` will always indicate an address mismatch, because it does a bitwise comparison, and all DTLS packets are dropped even if addresses and ports match.
`ast_sockaddr_from_pj_sockaddr()` now checks whether the length fields are available on the current …
> res_pjproject: Fix DTLS client check failing on some platforms

- pbx/pbx_ael.c
This fixes crashes/hangs I noticed with Asterisk 20.3.0 and 20.13.0 and quickly found out,
that the AEL module doesn't do proper cleanup when it fails to load.
This happens for example when there are syntax errors and AEL fails to compile in which case pbx_load_module()
returns an error but load_module() doesn't then unregister CLI cmds and the application.
> pbx_ael: unregister AELSub application and CLI commands on module load failure

- channels/chan_iax2.c
- channels/iax2/parser.c
* Update Dial() documentation for IAX2 to include syntax for RSA public key names.
* Add additional details to a couple warnings to provide more context when an undecodable frame is received.
Resolves: #1206
> chan_iax2: Minor improvements to documentation and warning messages.

- apps/app_meetme.c
app_meetme is deprecated but wasn't removed as planned in 21, so remove the inaccurate removal version.
Resolves: #1224
> app_meetme: Remove inaccurate removal version from xmldocs.

- funcs/func_callerid.c
ANI II is always supposed to be formatted as two digits, so zero pad when formatting it if necessary.
Resolves: #1222
> func_callerid: Always format ANI2 as two digits.

- include/asterisk/lock.h
When DEBUG_THREADS is defined, lock.h uses strerror(), which is defined
in the libc string.h file, to print warning messages. If the including
source file doesn't include string.h then strerror() won't be found and
and compile errors will be thrown. Since lock.h depends on this, string.h
is now included from there if DEBUG_THREADS is defined.  This way, including
source files don't have to worry about it.
> lock.h: Add include for string.h when DEBUG_THREADS is defined.

- apps/Makefile
Ignore gcc warning about writing 32 bytes into a region of size 6, since we check that we don't go out of bounds for each byte.
Resolves: #1088
> app_sms: Ignore false positive stringop-overflow warning.

- Makefile
- configs/samples/asterisk.conf.sample
- include/asterisk/channel.h
- include/asterisk/channel_internal.h
- include/asterisk/options.h
- main/Makefile
- main/asterisk.c
- main/channel.c
- main/channel_internal_api.c
- main/channel_private.h
- main/channelstorage.c
- main/channelstorage.h
- main/channelstorage_ao2_legacy.c
- main/channelstorage_cpp_map_name_id.cc
- main/channelstorage_makeopts.xml
- main/options.c
Full details: http://s.asterisk.net/dc679ec3
The previous proof-of-concept showed that the cpp_map_name_id alternate
storage backed performed better than all the others so this final PR
adds only that option.  You still need to enable it in menuselect under
the "Alternate Channel Storage Backends" category.
To select which one is used at runtime, set the "channel_storage_backend"
option in asterisk.conf to one of the values described in
asterisk.conf.sample.  The default remains "ao2_legacy".
UpgradeNote: With this release, you can now select an alternate channel
storage backend based on C++ Maps.  Using the new backend may increase
performance and reduce the chances of deadlocks on heavily loaded systems.
For more information, see http://s.asterisk.net/dc679ec3
> Alternate Channel Storage Backends

- res/res_pjsip_nat.c
When a call is transfered via dialplan behind a NAT, the
host portion of the Contact header in the 302 will no longer
be over-written with the external NAT IP and will retain the
hostname.
Fixes: #1141
> res_pjsip_nat.c: Do not overwrite transfer host

- main/manager.c
We have a use-case where we generate a *lot* of events on the AMI, and
then when doing `manager show eventq` we would see some events which
would linger for hours or days in there. Obviously something was leaking.
Testing allowed us to track down this logic bug in the ref-counting on
the event purge.
Reproducing the bug was not super trivial, we managed to do it in a
production-like load testing environment with multiple AMI consumers.
The race condition itself:
1. something allocates and links `session`
2. `purge_sessions` iterates over that `session` (takes ref)
3. `purge_session` correctly de-referencess that session
4. `purge_session` re-evaluates the while() loop, taking a reference
5. `purge_session` exits (`n_max > 0` is false)
6. whatever allocated the `session` deallocates it, …
> manager.c: Invalid ref-counting when purging events

- menuselect/menuselect_gtk.c
This patch resolves a build failure in `menuselect_gtk.c` when running
`make menuconfig` on Fedora 42. The new version of GTK introduced stricter
type checking for callback signatures.
Changes include:
- Add wrapper functions to match the expected `void (*)(void)` signature.
- Update `menu_items` array to use these wrappers.
Fixes: #1243
> menuselect: Fix GTK menu callbacks for Fedora 42 compatibility

- res/res_audiosocket.c
The added retry mechanism addresses an issue that arises when fragmented TCP packets are received, each containing only a portion of an AudioSocket packet. This situation can occur if the external service sending the AudioSocket data has Nagle's algorithm enabled.
> res_audiosocket.c: Add retry mechanism for reading data from AudioSocket

- configs/samples/asterisk.conf.sample
- configs/samples/cli_permissions.conf.sample
- include/asterisk/options.h
- main/asterisk.c
- main/options.c
UserNote: A new asterisk.conf option 'disable_remote_console_shell' has
been added that, when set, will prevent remote consoles from executing
shell commands using the '!' prefix.
Resolves: #GHSA-c7p6-7mvq-8jq2
> asterisk.c: Add option to restrict shell access from remote consoles.

- apps/app_sms.c
This fixes bugs in SMS messaging to SMS-capable analog phones that prevented app_sms.c from talking to phones using SMS protocol 2.
- Fix MORX message reception (from phone to Asterisk) in SMS protocol 2
- Fix MTTX message transmission (from Asterisk to phone) in SMS protocol 2
One of the bugs caused messages to have random characters and junk appended at the end up to the character limit. Another bug prevented Asterisk from sending messages from Asterisk to the phone at all. A final bug caused the transmission from Asterisk to the phone to take a long time because app_sms.c did not hang up after correctly sending the message, causing the phone to have to time out and hang up in order to complete the message transmission.
This was tested with a Linksys PAP2T and with a GrandStream HT814, …
> app_sms.c: Fix sending and receiving SMS messages in protocol 2

- res/res_musiconhold.c
This relates to #829
This doesn't fully solve the Ops issue, but it solves the specific crash there.  Further PRs to follow.
In the specific crash the generator was still under construction when moh was being stopped, which then proceeded to close the stream whilst it was still in use.
> res_musiconhold: Appropriately lock channel during start.

- include/asterisk/pbx.h
- main/pbx.c
Under certain circumstances the context/extens/prio are set in the ast_async_goto, for example action Redirect.
In the situation that action Redirect is broken by GotoIf this info is changed.
that will causes confusion in dialplan execution.
Resolves: #1273
> pbx.c: when set flag AST_SOFTHANGUP_ASYNCGOTO, ast_explicit_goto should return -1.

- third-party/pjproject/patches/0010-Avoid_deadlock_between_transport_and_transaction.patch
Backport patch from upstream
* Avoid deadlock between transport and transaction https://github.com/pjsip/pjproject/commit/edde06f261ac
Issue described in
https://github.com/pjsip/pjproject/issues/4442
> bundled_pjproject: Avoid deadlock between transport and transaction

- channels/chan_websocket.c
- include/asterisk/http_websocket.h
- main/channel.c
- res/ari/resource_channels.c
- res/ari/resource_channels.h
- res/res_ari_channels.c
- res/res_http_websocket.c
- rest-api/api-docs/channels.json
* Created chan_websocket which can exchange media over both inbound and
outbound websockets which the driver will frame and time.
See http://s.asterisk.net/mow for more information.
* res_http_websocket: Made defines for max message size public and converted
a few nuisance verbose messages to debugs.
* main/channel.c: Changed an obsolete nuisance error to a debug.
* ARI channels: Updated externalMedia to include chan_websocket as a supported
transport.
UserNote: A new channel driver "chan_websocket" is now available. It can
exchange media over both inbound and outbound websockets and will both frame
and re-time the media it receives.
See http://s.asterisk.net/mow for more information.
UserNote: The ARI channels/externalMedia API now includes support for the
WebSocket transport provided by …
> Media over Websocket Channel Driver

- channels/chan_pjsip.c
When the RTP media source changes, such as after a blind transfer, the new source introduces a discontinuous timestamp. According to RFC 3550, Section 5.1, an RTP stream's timestamp for a given SSRC must increment monotonically and linearly.
To comply with the standard and avoid a large timestamp jump on the existing SSRC, a new SSRC is generated for the new media stream.
This change resolves known interoperability issues with certain SBCs (like Sonus/Ribbon) that stop forwarding media when they detect such a timestamp violation. This code uses the existing implementation from chan_sip.
Resolves: #927
> chan_pjsip.c: Change SSRC after media source change

- res/res_agi.c
> res_agi: Increase AGI command buffer size from 2K to 8K

- apps/app_queue.c
QUEUE_MEMBER_COUNT has been deprecated since at least 1.6, for fully duplicating functionality available in the QUEUE_MEMBER function; remove it now.
Resolves: #1341
UpgradeNote: The deprecated QUEUE_MEMBER_COUNT function has been removed; use QUEUE_MEMBER(<queue>,logged) instead.
> app_queue: Remove redundant/deprecated function.

- funcs/func_dialplan.c
Remove VALID_EXTEN, which was deprecated/superseded by DIALPLAN_EXISTS in Asterisk 11 (commit 8017b65bb97c4226ca7a3c7c944a9811484e0305), as DIALPLAN_EXISTS does the same thing and is more flexible.
Resolves: #1347
UpgradeNote: The deprecated VALID_EXTEN function has been removed. Use DIALPLAN_EXISTS instead.
> func_dialplan: Remove deprecated/redundant function.

- main/file.c
With `sounds_search_custom_dir = yes`, we are supposed to search for sounds in the `AST_DATA_DIR/sounds/custom` directory before searching the normal directories.
Unfortunately, a recent change (#1172) had a typo resulting in the "custom" directory not being searched.  This change restores this expected behavior.
Resolves: #1353
> file.c: with "sounds_search_custom_dir = yes", search "custom" directory

- pbx/pbx_lua.c
This can be reproduced under certain curcomstences.
For example: call app.playback from lua with invalid data: app.playback({}).
pbx_lua.c will try to get data for this playback using lua_tostring function.
This function returs NULL for everything but strings and numbers.
Then, it calls term_color with NULL data.
term_color function can call(if we don't use vt100 compat term)
ast_copy_string with NULL inbuf which cause segfault. bt example:
ast_copy_string (size=8192, src=0x0, dst=0x7fe44b4be8b0)
at /usr/src/asterisk/asterisk-20.11.0/include/asterisk/strings.h:412
Resolves: https://github.com/asterisk/asterisk/issues/1363
> pbx_lua.c: segfault when pass null data to term_color function

- funcs/func_frame_drop.c
Handle allocation failure and simplify the allocation using asprintf.
Resolves: #1366
> func_frame_drop: Handle allocation failure properly.

- tests/test_res_prometheus.c
curl_easy_setopt expects long types, so be explicit.
Resolves: #1369
> test_res_prometheus: Fix compilation failure on Debian 13.

- funcs/func_frame_drop.c
- main/channel.c
Add debug messages in scenarios where frames that are usually processed are dropped or skipped.
Resolves: #1371
> func_frame_drop: Add debug messages for dropped frames.

- apps/app_queue.c
- configs/samples/queues.conf.sample
In many asterisk-based systems, the pause reason is used to separate
pauses by type,and logically, changing the reason defines two intervals
that should be accounted for separately. The introduction of a new
option allows me to separate the intervals of operator inactivity in
the log by the event of unpausing.
UserNote: Add new global option 'log_unpause_on_reason_change' that
is default disabled. When enabled cause addition of UNPAUSE event on
every re-PAUSE with reason changed.
> app_queue.c: Add new global 'log_unpause_on_reason_change'

- channels/chan_websocket.c
Added DTMF messages to the chan_websocket feature.
When a user presses DTMF during a call over chan_websocket it will send a message like:
"DTMF_END digit:1"
Resolves: https://github.com/asterisk/asterisk-feature-requests/issues/70
> chan_websocket.c: Add DTMF messages

- apps/app_externalivr.c
> app_externalivr: Prevent out-of-bounds read during argument processing.

- res/ari/resource_bridges.c
- res/ari/resource_bridges.h
- res/res_ari_bridges.c
- rest-api/api-docs/bridges.json
The bridge play and record APIs were forcing the Announcer/Recorder channel
to slin8 which meant that if you played or recorded audio with a sample
rate > 8K, it was downsampled to 8K limiting the bandwidth.
* The /bridges/play REST APIs have a new "announcer_format" parameter that
allows the caller to explicitly set the format on the "Announcer" channel
through which the audio is played into the bridge.  If not specified, the
default depends on how many channels are currently in the bridge.  If
a single channel is in the bridge, then the Announcer channel's format
will be set to the same as that channel's.  If multiple channels are in the
bridge, the channels will be scanned to find the one with the highest
sample rate and the Announcer channel's format will be set to the slin
format …
> ARI: The bridges play and record APIs now handle sample rates > 8K correctly.

- funcs/func_scramble.c
The previous lack of an example made it ambiguous if the arguments went inside the function arguments or were part of the right-hand value.
Resolves: #1485
> func_scramble: Add example to XML documentation.

- main/config_options.c
When running "config show help <module>", if no XML documentation exists for the specified module, "Module <module> not found." is returned, which is misleading if the module is loaded but simply has no XML documentation for its config. Improve the message to clarify that the module may simply have no config documentation.
Resolves: #1489
> config_options.c: Improve misleading warning.

- funcs/func_math.c
Add a function (DIGIT_SUM) which returns the digit sum of a number.
Resolves: #1499
UserNote: The DIGIT_SUM function can be used to return the digit sum of a number.
> func_math: Add DIGIT_SUM function.

- funcs/func_callerid.c
The Dial() application does not propagate DNID fields, which is counter to the behavior of the other Caller ID fields. This behavior is likely intentional since the use of Dial theoretically suggests a new dialed number, but document this caveat to inform users of it.
Resolves: #1519
> func_callerid: Document limitation of DNID fields.

- channels/chan_websocket.c
Some of the tests in process_text_message() were still comparing to the
websocket message payload instead of the "command" string.
Resolves: #1525
> chan_websocket.c: Change payload references to command instead.
