asterisk/asterisk

- LICENSE
This updates the link for the trademark policy to the current location.
Resolves: #43
> LICENSE: Update link to trademark policy.

- main/xml.c
If processing an XInclude results in new `<xi:include>` elements, we need to run XInclude processing again. This continues until no replacement occurs or an error is encountered.
There is a separate issue with dynamic strings (ast_str) that will be addressed separately.
Resolves: #65
> xml.c: Process XML Inclusions recursively.

- res/ari/resource_bridges.h
- res/res_stasis.c
- res/stasis/stasis_bridge.c
- res/stasis/stasis_bridge.h
- rest-api/api-docs/bridges.json
Resolves: https://github.com/asterisk/asterisk/issues/91
> res_stasis.c: Add new type 'sdp_label' for bridge creation.

- main/manager.c
Adds a new AMI action (CoreShowChannelMap) that takes in a channel name
and provides a list of all channels that are connected to that channel,
following local channel connections as well.
Resolves: #104
UserNote: New AMI action CoreShowChannelMap has been added.
> AMI: Add CoreShowChannelMap action.

- contrib/ast-db-manage/config/versions/f5b0e7427449_add_loop_last_to_res_musiconhold.py
> ast-db-manage: Fix alembic branching error caused by #122.

- tests/test_stasis_endpoints.c
The channel_messages test was assuming that stasis would return
messages in a specific order.  This is an incorrect assumption as
message ordering was never guaranteed.  This was causing the test
to fail occasionally.  We now test all the messages for the
required message types instead of testing one by one.
Resolves: #158
> test_stasis_endpoints.c: Make channel_messages more stable

- res/res_crypto.c
- res/res_pjsip/pjsip_transport_events.c
> res_crypto, res_pjsip: compilation fail on 32-bit

- main/utils.c
Adds last locked and unlocked timestamps as well as a
counter for the number of times the lock has been
attempted (vs locked/unlocked) to debug output printed
using the DEBUG_THREADS option.
Resolves: #110
> utils: add lock timestamps for DEBUG_THREADS

- res/res_geolocation/geoloc_config.c
> res_geolocation: Ensure required 'location_info' is present.

- apps/app_queue.c
The app_queue module provides both an AMI action and a CLI command to change the priority of a caller in a queue. Up to now this change of priority has only been reflected to new callers into the queue.
This change adds an "immediate" option to both the AMI action and CLI command which immediately applies the priority change respective to the other callers already in the queue. This can allow, for example, a caller to be placed at the head of the queue immediately if their priority is sufficient.
Resolves: #202
UserNote: The 'queue priority caller' CLI command and 'QueueChangePriorityCaller' AMI action now have an 'immediate' argument which allows the caller priority change to be reflected immediately, causing the position of a caller to move within the queue depending on the priorities …
> app_queue: Add support for applying caller priority change immediately.

- apps/app_stack.c
This reverts commit 617dad4cba1513dddce87b8e95a61415fb587cf1.
apps/app_stack.c: Revert buggy gosub patch
This seems to break the case when a predial macro calls a gosub.
When the gosub calls return, the Return function outputs:
app_stack.c:423 return_exec: Return without Gosub: stack is empty
This returns -1 to the calling macro, which returns to app_dial
and causes the call to hangup instead of proceeding with the macro
that invoked the gosub.
Resolves: #253
> Revert "app_stack: Print proper exit location for PBXless channels."

- apps/app_audiosocket.c
> app_audiosocket: Fixed timeout with -1 to avoid busy loop.

- apps/app_voicemail.c
Resolve for loop initial declarations added in cli changes.
Resolves: #275
> app_voicemail: Fix for loop declarations

- apps/app_dial.c
If the called party hangs up while digits are being sent, -1 is returned to indicate so, but app_dial
was not checking the return value, resulting in
the hangup being lost and looping forever until
the caller manually hangs up the channel. We now
abort if digit sending fails.
ASTERISK-29428 #close
Resolves: #281
> app_dial: Fix infinite loop when sending digits.

- res/res_pjsip_session.c
Handle session interval lower than endpoint's configured minimum timer when sending first answer. Timer setting is checked during this step and needs to handled appropriately. Otherwise no response will be sent at all.
> res_pjsip_session: Send Session Interval too small response

- channels/chan_rtp.c
Resolves: #298
UserNote: The dial string option 'g' was added to the UnicastRTP channel which enables RTP glue and therefore native RTP bridges with those channels.
> chan_rtp: Implement RTP glue for UnicastRTP channels

- res/res_stasis_recording.c
> res_stasis_recording.c: Save recording state when unmuted.

- channels/chan_iax2.c
Improves and adds some logging to make it easier
for users to debug authentication issues.
Resolves: #286
> chan_iax2: Improve authentication debugging.

- res/res_pjsip_transport_websocket.c
From the gdb information, ast_websocket_read reads a message successfully,
then transport_read is called in the serializer. During execution of pjsip_transport_down,
ws_session->stream->fd is closed; ast_websocket_read encounters an error and exits the while loop.
After executing transport_shutdown, the transport's reference count becomes 0, causing a crash when sending SIP messages.
This was due to pjsip_transport_dec_ref executing earlier than pjsip_rx_data_clone, leading to this issue.
In websocket_cb executeing pjsip_transport_add_ref, this we now ensure the transport is not destroyed while in the loop.
Resolves: asterisk#299
> res_pjsip_transport_websocket: Prevent transport from being destroyed before message finishes.

- apps/app_queue.c
> app_queue.c: Emit unpause reason with PauseQueueMember event.

- apps/app_voicemail.c
This adds an AMI event that is emitted whenever a
mailbox password is successfully changed, allowing AMI consumers to process these.
UserNote: The VoicemailPasswordChange event is
now emitted whenever a mailbox password is updated, containing the mailbox information and the new
password.
Resolves: #398
> app_voicemail: Add AMI event for mailbox PIN changes.

- apps/app_directory.c
This adds optional ADSI support to the Directory
application, which allows callers with ADSI CPE
to navigate the Directory system significantly
faster than is possible using the audio prompts.
Callers can see the directory name (and optionally extension) on their screenphone and confirm or
reject a match immediately rather than waiting
for it to be spelled out, enhancing usability.
Resolves: #356
> app_directory: Add ADSI support to Directory.

- res/ari/resource_channels.c
> resource_channels.c: Explicit codec request when creating UnicastRTP.

- res/res_rtp_asterisk.c
In 5ac5c2b0 we defined `OPENSSL_SUPPRESS_DEPRECATED` to silence deprecation warnings. This commit switches over to using non-deprecated API.
> res_rtp_asterisk.c: Update for OpenSSL 3+.

- main/config.c
If the script referenced by `#exec` does not exist, writes anything to stderr, or exits abnormally or with a non-zero exit status, we log that to Asterisk's error logging channel.
Additionally, write out a warning if the script produces no output.
Fixes #259
> config.c: Log #exec include failures.

- res/res_odbc.c
There are valid scenarios where res_odbc's connection pool might have some dead
or stuck connections while others are healthy (imagine network
elements/firewalls/routers silently timing out connections to a single DB and a
single IP address, or a heterogeneous connection pool connected to potentially
multiple IPs/instances of a replicated DB using a DNS front end for load
balancing and one replica fails).
In order to time out those unhealthy connections without blocking access to
other parts of Asterisk that may attempt access to the connection pool, it would
be beneficial to not lock/block access around the entire pool in
_ast_odbc_request_obj2 while doing potentially blocking operations on connection
pool objects such as the connection_dead() test, odbc_obj_connect(), or by …
> res_odbc.c: Allow concurrent access to request odbc connections

- pbx/pbx_config.c
`pbx_config` subscribes to manager events to capture the `FullyBooted` event but fails to unsubscribe if the module is loaded after that event fires. If the module is unloaded, a crash occurs the next time a manager event is raised.
We now unsubscribe when the module is unloaded if we haven't already unsubscribed.
Fixes #470
> pbx_config.c: Don't crash when unloading module.

- main/manager.c
When using AMI GetConfig, it was possible to access files outside of the
Asterisk configuration directory by using filenames with ".." and "./"
even while live_dangerously was not enabled. This change resolves the
full path and ensures we are still in the configuration directory before
attempting to access the file.
> manager.c: Prevent path traversal with GetConfig.

- apps/app_if.c
This fixes faulty branching logic for the
EndIf application. Instead of computing
the next priority, which should be done
for false conditionals or ExitIf, we should
simply advance to the next priority.
Resolves: #341
> app_if: Fix faulty EndIf branching.

- apps/confbridge/conf_config_parser.c
The numeric bridge profile options `internal_sample_rate` and `maximum_sample_rate` are documented to accept the special values `auto` and `none`, respectively. While these values currently work, they also emit warnings when used which could be confusing for users.
In passing, also ensure that we only accept the documented range of sample rate values between 8000 and 192000.
Fixes #546
> app_confbridge: Don't emit warnings on valid configurations.

- apps/app_chanspy.c
Adds the 'D' option to app chanspy that causes the input and output
frames of the spied channel to be interleaved in the spy output frame.
This allows the input and output of the spied channel to be decoded
separately by the receiver.
If the 'o' option is also set, the 'D' option is ignored as the
audio being spied is inherently one direction.
Fixes: #569
UserNote: The ChanSpy application now accepts the 'D' option which
will interleave the spied audio within the outgoing frames. The
purpose of this is to allow the audio to be read as a Dual channel
stream with separate incoming and outgoing audio. Setting both the
'o' option and the 'D' option and results in the 'D' option being
ignored.
> app_chanspy: Add 'D' option for dual-channel audio

- contrib/ast-db-manage/config/versions/24c12d8e9014_add_user_agent_header_to_ps_.py
- res/res_pjsip_outbound_registration.c
> res_pjsip_outbound_registration.c: Add User-Agent-Header override

- apps/app_speech_utils.c
Adds 'p' option to SpeechBackground() application.
With this option, when the app timeout is reached,
whatever the backend speech engine collected will
be returned as if it were the final, full result.
(This works for engines that make partial results.)
Resolves: #572
UserNote: The words might be less than the best.
> app_speech_utils.c: Allow partial speech results.

- main/dsp.c
If ast_dsp_process is called with a codec besides slin, ulaw, or alaw, a warning is logged that in-band DTMF is not supported, but this message is not always appropriate or correct, because ast_dsp_process is much more generic than just DTMF detection.
This logs a more generic message in those cases, and also improves codec-mismatch logging throughout dsp.c by ensuring incompatible codecs are printed out.
Resolves: #595
> dsp.c: Fix and improve potentially inaccurate log message.

- README.md
Removed outdated link http://www.quicknet.net from README.md
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
> README.md: Removed outdated link

- contrib/ast-db-manage/config/versions/4da0c5f79a9c_create_tables.py
> alembic: Quote new MySQL keyword 'qualify.'

- res/prometheus/bridges.c
- tests/test_res_prometheus.c
The prometheus exposition format requires each line to be unique[1]. This is handled by struct prometheus_metric having a list of children that is managed when registering a metric. In case the scrape callback is used, it is the responsibility of the implementation to handle this correctly.
Originally the bridge callback didn't handle NULL snapshots, the crash fix lead to NULL metrics, and fixing that lead to duplicates.
The original code assumed that snapshots are not NULL and then relied on "if (i > 0)" to establish the parent/children relationship between metrics of the same class. This is not workerable as the first bridge might be invisible/lacks a snapshot.
Fix this by keeping a separate array of the first metric by class. Instead of relying on the index of the bridge, check whether …
> res_prometheus: Fix duplicate output of metric and help text

- main/pbx_variables.c
It is possible for dialplan to result in an infinite recursion of variable substitution, which eventually leads to stack overflow. If we detect this, abort
substitution and log an error for the user to fix
the broken dialplan.
Resolves: #480
> pbx_variables.c: Prevent SEGV due to stack overflow.

- menuselect/menuselect.c
Improve some of the formatting from
dd3f17c699e320d6d30c94298d8db49573ba28da
(#521).
> menuselect: Minor cosmetic fixes.

- contrib/ast-db-manage/env.py
SQLAlchemy 2.0 changed the way that commits/rollbacks are handled causing the final `UPDATE` to our `alembic_version_<whatever>` tables to be rolled back instead of committed.
We now use one connection to determine which `alembic_version_<whatever>` table to use and another to run the actual migrations. This prevents the erroneous rollback.
This change is compatible with both SQLAlchemy 1.4 and 2.0.
> alembic: Fix compatibility with SQLAlchemy 2.0+.

- res/res_pjsip_refer.c
There was functionality in chan_sip to get REFER headers, with GET_TRANSFERRER_DATA variable. This commit implements the same functionality in pjsip, to ease transfer from chan_sip to pjsip.
Fixes: #579
UserNote: the GET_TRANSFERRER_DATA dialplan variable can now be used also in pjsip.
> res_pjsip_refer.c: Allow GET_TRANSFERRER_DATA

- channels/chan_dahdi.c
* Add an AMI action to correspond to the "dahdi show status" command, allowing span information to be retrieved via AMI.
* Show span number and sig type in "dahdi show channels".
Resolves: #673
> chan_dahdi: Add DAHDIShowStatus AMI action.

- main/manager.c
* Added the AuthType and Key parameters for MD5 authentication.
* Added the Events parameter.
Resolves: #689
> manager.c: Add missing parameters to Login documentation

- contrib/ast-db-manage/config/versions/6c475a93f48a_correct_nullability_of_pjsip_id_columns.py
> alembic: Correct NULLability of PJSIP id columns.

- contrib/ast-db-manage/config/versions/6c475a93f48a_correct_nullability_of_pjsip_id_columns.py
This PR is specific to certified/20.7
Fixes #695
> alembic: Correct NULLability of PJSIP id columns. (certified/20.7)

- configs/samples/pjsip.conf.sample
- contrib/ast-db-manage/config/versions/bd9c5159c7ea_revert_d5122576cca8_add_transport_.py
- include/asterisk/res_pjsip.h
- res/res_pjsip/pjsip_config.xml
- res/res_pjsip/pjsip_configuration.c
- res/res_pjsip_endpoint_identifier_ip.c
This reverts PR #602
Resolves: #GHSA-qqxj-v78h-hrf9
> Revert "res_pjsip_endpoint_identifier_ip: Add endpoint identifier transport address."

- addons/chan_ooh323.c
Change-Id: I00d79a807dd0fea9e42fca919aa2fb0b71cdf20e
> chan_ooh323: Fix R/0 typo in docs

- cdr/cdr_pgsql.c
Missing or corrupt cdr_pgsql.conf configuration file can cause the second attempt to load the PostgreSQL CDR module to crash Asterisk via the Command Line Interface because a null CLI command is registered on the first failed attempt to load the module.
Resolves: #736
> Permit multiple attempts to load PostgreSQL CDR module.

- apps/app_voicemail.c
- configs/samples/voicemail.conf.sample
- include/asterisk/logger.h
- main/app.c
- **app_voicemail_odbc: Allow audio to be kept on disk**
- **logger.h: Include SCOPE_CALL_WITH_INT_RESULT() in non-dev-mode builds.**
> app_voicemail_odbc: Allow audio to be kept on disk - cert-20.7

- configs/samples/voicemail.conf.sample
...and removed an errant trailing space.
Resolves: #819
> voicemail.conf.sample: Fix ':' comment typo

- res/res_pjsip_config_wizard.c
The way we have been initializing the config wizard prevented it
from registering its objects if res_pjsip happened to load
before it.
* We now use the object_type_registered sorcery observer to kick
things off instead of the wizard_mapped observer.
* The load_module function now checks if res_pjsip has been loaded
already and if it was it fires the proper observers so the objects
load correctly.
Resolves: #816
UserNote: The res_pjsip_config_wizard.so module can now be reloaded.
> res_pjsip_config_wizard.c: Refactor load process

- main/rtp_engine.c
There can be empty slots in payload_mapping_tx corresponding to
dynamic payload types that haven't been seen before so we now
check for NULL before attempting to use 'type' in the call to
ast_format_cmp.
Note: Currently only chan_sip calls ast_rtp_codecs_payloads_unset()
Resolves: #822
> rtp_engine.c: Prevent segfault in ast_rtp_codecs_payloads_unset()

- configs/samples/stasis.conf.sample
- include/asterisk/stasis_channels.h
- main/stasis.c
- main/stasis_channels.c
- res/ari/ari_model_validators.c
- res/ari/ari_model_validators.h
- res/res_tonedetect.c
- rest-api/api-docs/events.json
Fixes: #811
Refrained from adding any JSON blob to the message. Perhaps it should be part of a separate PR if anyone wants to build on this later on.
> feat: ARI "ChannelToneDetected" event

- res/res_pjsip_logger.c
> res_pjsip_logger.c: Fix 'OPTIONS' tab completion.

- configs/samples/stir_shaken.conf.sample
They should be private_key_file.
Resolves: #854
> stir_shaken.conf.sample: Fix bad references to private_key_path

- apps/app_voicemail.c
...instead of trying to calculate the length of the buffer needed
manually.
> app_voicemail: Use ast_asprintf to create mailbox SQL query

- main/autoservice.c
It's possible that ast_autoservice_stop is called within the autoservice thread.
In this case the autoservice thread is stuck in an endless sleep.
To avoid endless sleep ast_autoservice_stop must check that it's not called
within the autoservice thread.
Fixes: #763
> autoservice: Do not sleep if autoservice_stop is called within autoservice thread

- res/res_stir_shaken.c
* If the call to ast_config_load() returns CONFIG_STATUS_FILEINVALID,
check_for_old_config() now returns LOAD_DECLINE instead of continuing
on with a bad pointer.
* If CONFIG_STATUS_FILEMISSING is returned, check_for_old_config()
assumes the config is being loaded from realtime and now returns
LOAD_SUCCESS.  If it's actually not being loaded from realtime,
sorcery will catch that later on.
* Also refactored the error handling in load_module() a bit.
Resolves: #884
> res_stir_shaken.c: Fix crash when stir_shaken.conf is invalid

- contrib/ast-db-manage/config/versions/801b9fced8b7_add_generator_data_to_ps_subscription_.py
> res_pjsip_pubsub: Persist subscription 'generator_data' in sorcery

- main/manager.c
When using the ModuleLoad AMI action, it was possible to traverse
upwards through the directories to files outside of the configured
modules directory. We decided it would be best to restrict access to
modules exclusively in the configured directory. You will now get an
error when the specified module is outside of this limitation.
Fixes: #897
UserNote: The ModuleLoad AMI action now restricts modules to the
configured modules directory.
> manager.c: Restrict ModuleLoad to the configured modules directory.

- channels/chan_dahdi.c
In some circumstances, it is possible for the do_monitor thread to erroneously think that a line is on-hook and send an MWI FSK spill to it when the line is really off-hook and no MWI should be sent. Commit 0a8b3d34673277b70be6b0e8ac50191b1f3c72c6 previously fixed this issue in a more readily encountered scenario, but it has still been possible for MWI to be sent when it shouldn't be. To robustly fix this issue, query DAHDI for the hook status to ensure we don't send MWI on a line that is actually still off hook.
Resolves: #928
> chan_dahdi: Never send MWI while off-hook.

- channels/chan_sip.c
> chan_sip.c: Fix `__sip_reliable_xmit` build error

- funcs/func_evalexten.c
This adds an EVAL_SUB function, which is similar to the existing EVAL_EXTEN function but significantly more powerful, as it allows executing arbitrary dialplan and capturing its return value as the function's output. While EVAL_EXTEN should be preferred if it is possible to use it, EVAL_SUB can be used in a wider variety of cases and allows arbitrary computation to be performed in a dialplan function call, leveraging the dialplan.
Resolves: #951
> func_evalexten: Add EVAL_SUB function.

- configs/samples/chan_dahdi.conf.sample
- configs/samples/extensions.conf.sample
- configs/samples/pjsip.conf.sample
- configs/samples/res_snmp.conf.sample
Cleaned some dead links. Replaced word wiki with
either docs or link to https://docs.asterisk.org/
Resolves: #974
> samples: remove and/or change some wiki mentions

- main/audiohook.c
audiohook.c: resolving the issue with audiohook both reading when packet loss on one side of the call
When there is 0% packet loss on one side of the call and 15% packet loss on the other side, reading frame is often failed when reading direction_both audiohook. when read_factory available = 0, write_factory available = 320; i think write factory is usable read; because after reading one frame, there is still another frame that can be read together with the next read factory frame.
Resolves: #851
> audiohook.c: resolving the issue with audiohook both reading when packet loss on one side of the call

- res/res_odbc.c
Whenever a slot is freed up due to a dead connection, or a connection failure, wake up another consumer.
Also fix the pointer log for ODBC handle %p dead which would always reflect NULL.
> res_odbc: release threads from potential starvation.

- third-party/pjproject/patches/0000-configure-ssl-library-path.patch
- third-party/pjproject/pjproject-2.14.1.tar.bz2.md5
- third-party/pjproject/pjproject-2.15.1.tar.bz2.md5
- third-party/versions.mak
Resolves: asterisk#1016
UserNote: Bundled pjproject has been upgraded to 2.15.1. For more
information visit pjproject Github page: https://github.com/pjsip/pjproject/releases/tag/2.15 and https://github.com/pjsip/pjproject/releases/tag/2.15.1
> Upgrade bundled pjproject to 2.15.1

- contrib/ast-db-manage/queue_log.ini.sample
First time contributor here.
The other files have mysql by default.  
This was causing an inconsistency in a bash script i use to install asterisk.
> normalize contrib/ast-db-manage/queue_log.ini.sample

- res/res_pjproject.c
Fix typo (OpenmSSL->OpenSSL) mentioned by bkford in #972
> res_pjproject: Fix typo (OpenmSSL->OpenSSL)

- main/manager.c
Also correct the spelling of 'privileges.'
> manager.c: Rename restrictedFile to is_restricted_file.

- channels/pjsip/dialplan_functions_doc.xml
> dialplan_functions_doc.xml: Document PJSIP_MEDIA_OFFER's `media` argument.

- channels/chan_iax2.c
Currently, when receiving an unauthenticated call, we keep track of the negotiated format in the chosenformat, which allows us to later create the channel using the right format. However, this was not done for authenticated calls. This meant that in certain circumstances, if we had not yet received a voice frame from the peer, only certain other types of frames (e.g. text), there were no variables containing the appropriate frame. This led to problems in the jitterbuffer callback where we unnecessarily bailed out of retrieving a frame from the jitterbuffer. This was logic intentionally added in commit 73103bdcd5b342ce5dfa32039333ffadad551151 in response to an earlier regression, and while this prevents crashes, it also backlogs legitimate frames unnecessarily.
The abort logic was …
> chan_iax2: Always set chosenformat upon call connection.

- res/res_pjsip_authenticator_digest.c
The return code fom digest_check_auth wasn't explicitly being initialized.
The return code also wasn't explicitly set to CHALLENGE when challenges
were sent.  When optimization was turned off (DONT_OPTIMIZE), the compiler
was setting it to "0"(CHALLENGE) which worked fine.  However, with
optimization turned on, it was setting it to "1" (SUCCESS) so if there was
no incoming Authorization header, the function was returning SUCCESS to the
distributor allowing the request to incorrectly succeed.
The return code is now initialized correctly and is now explicitly set
to CHALLENGE when we send challenges.
> res_pjsip_authenticator_digest: Fix issue with missing auth and DONT_OPTIMIZE

- res/res_prometheus.c
This should resolve the Prometheus error:
> Error scraping target: non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target.
Resolves: #1075
> res_prometheus.c: Set Content-Type header on /metrics response.

- res/res_pjsip_authenticator_digest.c
When an incoming request can't be matched to an endpoint, the "artificial"
auth object is used to create a challenge to return in a 401 response and we
emit a "No matching endpoint found" log message. If the client then responds
with an Authorization header but the request still can't be matched to an
endpoint, the verification will fail and, as before, we'll create a challenge
to return in a 401 response and we emit a "No matching endpoint found" log
message.  HOWEVER, because there WAS an Authorization header and it failed
verification, we should have also been emitting a "Failed to authenticate"
log message but weren't because there was a check that short-circuited that
it if the artificial auth was used.  Since many admins use the "Failed to
authenticate" message with log parsers like …
> res_pjsip_authenticator_digest: Make correct error messages appear again.

- res/ari/resource_channels.c
Between ast_ari_channels_external_media(), external_media_rtp_udp(),
and external_media_audiosocket_tcp(), the `variables` structure being passed
around wasn't being cleaned up properly when there was a failure.
* In ast_ari_channels_external_media(), the `variables` structure is now
defined with RAII_VAR to ensure it always gets cleaned up.
* The ast_variables_destroy() call was removed from external_media_rtp_udp().
* The ast_variables_destroy() call was removed from
external_media_audiosocket_tcp(), its `endpoint` allocation was changed to
to use ast_asprintf() as external_media_rtp_udp() does, and it now
returns an error on failure.
* ast_ari_channels_external_media() now checks the new return code from
external_media_audiosocket_tcp() and sets the appropriate error response. …
> resource_channels.c: Fix memory leak in ast_ari_channels_external_media.

- cdr/cdr_beanstalkd.c
- cdr/cdr_custom.c
- cdr/cdr_pgsql.c
- cdr/cdr_sqlite3_custom.c
> docs: Fix typos in cdr/

- main/config.c
Commit 3cab4e7ab4a3ae483430d5f5e8fa167d02a8128c introduced a regression by causing the wrong pointers to be used in certain (more complex) cases. We now take care to ensure the exact same pointers are used as before that commit, and simplify by eliminating the unnecessary second for loop.
Resolves: #1147
> config.c: Fix inconsistent pointer logic in ast_variable_update.

- README.md
* Outdated information has been removed.
* New links added.
* Placeholder added for link to change logs.
Going forward, the release process will create HTML versions of the README
and change log and will update the link in the README to the current
change log for the branch...
* In the development branches, the link will always point to the current
release on GitHub.
* In the "releases/*" branches and the tarballs, the link will point to the
ChangeLogs/ChangeLog-<version>.html file in the source directory.
* On the downloads website, the link will point to the
ChangeLog-<version>.html file in the same directory.
Resolves: #1131
> README.md: Updates and Fixes

- res/res_config_curl.c
> res_config_curl.c: Remove unnecessary warnings.

- main/file.c
With `sounds_search_custom_dir = yes` we first look to see if a sound file is present in the "custom" sound directory before looking in the standard sound directories.  We should not be issuing a WARNING log message if a sound cannot be found in the "custom" directory.
Resolves: https://github.com/asterisk/asterisk/issues/1170
> file.c: missing "custom" sound files should not generate warning logs

- apps/app_audiosocket.c
- channels/chan_audiosocket.c
- include/asterisk/channel.h
- include/asterisk/res_audiosocket.h
- res/res_audiosocket.c
- **audiosocket: fix timeout, fix dialplan app exit, server address in logs**
- **asterisk/channel.h: fix documentation for 'ast_waitfor_nandfds()'**
- **audiosocket: added support for DTMF frames**
> audiosocket improvements

- apps/confbridge/confbridge_manager.c
> app_confbridge: Prevent crash when publishing channel-less event.

- main/channel.c
When queueing a channel to be hung up a cause code can be specified in one of two ways:
1. ast_queue_hangup_with_cause This function takes in a cause code and queues it as part of the hangup request, which ultimately results in it being set on the channel.
2. ast_channel_hangupcause_set + ast_queue_hangup This combination sets the hangup cause on the channel before queueing the hangup instead of as part of that process.
In the #2 case the ChannelHangupRequest event would not contain the cause code. For consistency if a cause code has been set on the channel it will now be added to the event.
Resolves: #1197
> channel: Always provide cause code in ChannelHangupRequest.

- apps/app_audiosocket.c
- apps/app_cdr.c
- apps/app_confbridge.c
- apps/app_dial.c
- apps/app_echo.c
- apps/app_externalivr.c
- apps/app_jack.c
- apps/app_meetme.c
- apps/app_minivm.c
- apps/app_mixmonitor.c
- apps/app_morsecode.c
- apps/app_mp3.c
- apps/app_queue.c
- apps/app_saycounted.c
- apps/app_skel.c
- apps/app_sms.c
- apps/app_voicemail.c
- apps/app_waitforsilence.c
- apps/confbridge/conf_config_parser.c
- apps/confbridge/include/confbridge.h
> docs: Fix typos in apps/

- res/res_pjsip_caller_id.c
If the isup-oli was sent as a URI parameter, rather than a header parameter, it was not being parsed. Make sure we parse both if needed so the ANI2 is set regardless of which type of parameter the isup-oli is sent as.
Resolves: #1220
> res_pjsip_caller_id: Also parse URI parameters for ANI2.

- channels/chan_pjsip.c
When a call is transfered via DTMF feature code, the Transfer Target and
Transferer are bridged immediately.  This opens the possibilty of a race
condition between the creation of an INVITE and the bridge induced colp
update that can result in the set caller ID being over-written with the
transferer's default info.
Fixes: #1234
> chan_pjsip: Serialize INVITE creation on DTMF attended transfer

- res/res_pjsip_messaging.c
Incoming SIP MESSAGEs will now have their From header's display name
sanitized by replacing any characters < 32 (space) with a space.
Resolves: #GHSA-2grh-7mhv-fcfw
> res_pjsip_messaging.c: Mask control characters in received From display name

- res/res_agi.c
DeadAGI was deprecated 7 years ago, in Asterisk 15, as it duplicates functionality in the AGI app.
This removes the application.
Resolves: #258
UpgradeNote: The DeadAGI application, which was
deprecated in Asterisk 15, has now been removed.
The same functionality is available in the AGI app.
> res_agi: Remove deprecated DeadAGI application.

- res/res_pjsip_diversion.c
Based on the firing order of the PJSIP call-backs on a redirect, it was possible for
the Diversion header to not be included in the outgoing 181 response to the UAC and
the INVITE to the UAS.
This change moves the Diversion header processing to an earlier PJSIP callback while also
preventing the corresponding update that can cause a duplicate 181 response when processing
the header at that time.
Resolves: #1349
> res_pjsip_diversion: resolve race condition between Diversion header processing and redirect

- main/xmldoc.c
If you do a `core show application Dial`, you'll see it's kind of a mess.
Indents are wrong is some places, examples are printed in black which makes
them invisible on most terminals, and the lack of line breaks in some cases
makes it hard to follow.
* Fixed the rendering of examples so they are indented properly and changed
the color so they can be seen.
* There is now a line break before each option.
* Options are now printed on their own line with all option content indented
below them.
Example from Dial before fixes:
```
Example: Dial 555-1212 on first available channel in group 1, searching
from highest to lowest
Example: Ringing FXS channel 4 with ring cadence 2
Example: Dial 555-1212 on channel 3 and require answer confirmation
...
O([mode]):
mode - With <mode> either not specified …
```
> xmldoc.c: Fix rendering of CLI output.

- res/res_pjsip_authenticator_digest.c
In the highly-unlikely event that get_authorization_hdr() couldn't find an
Authorization header in a request, trying to get the digest algorithm
would cauase a SEGV.  We now check that we have an auth header that matches
the realm before trying to get the algorithm from it.
Resolves: #GHSA-64qc-9x89-rx5j
> res_pjsip_authenticator_digest: Fix SEGV if get_authorization_hdr returns NULL.

- apps/app_waitforsilence.c
The functions WaitForNoise() and WaitForSilence() use the time() functions to calculate elapsed time, which causes the timer to fire on a whole second boundary, and the actual function execution time to fire the timer may be 1 second less than expected. This fix replaces time() with ast_tvnow().
Fixes: #1401
> app_waitforsilence.c: Use milliseconds to calculate timeout time

- main/sorcery.c
This change moves observer invocation from the use of a threadpool to a taskpool. The taskpool options have also been adjusted to ensure that at least one taskprocessor remains available at all times.
> sorcery: Move from threadpool to taskpool.

- channels/sig_analog.c
If Last Number Redial is used to redial, ensure that we do not wait for further digits. This was possible if the number that was last dialed is a prefix of another possible dialplan match. Since all we did is copy the number into the extension buffer, if other matches are now possible, there would thus be a timeout before the call went through. We now complete redialed calls immediaetly in all cases.
Resolves: #1483
> sig_analog: Eliminate potential timeout with Last Number Redial.

- res/res_fax.c
Document the channel variables currently set by SendFAX and ReceiveFAX.
Resolves: #1505
> res_fax: Add XML documentation for channel variables.

- apps/app_sf.c
Add a sorely needed option to set a timeout between digits, rather than for receiving the entire number. This is needed if the number of digits being sent is unknown by the receiver in advance. Previously, we had to wait for the entire timer to expire.
Resolves: #1493
UserNote: The 't' option for ReceiveSF now allows for a timer since
the last digit received, in addition to the number-wide timeout.
> app_sf: Add post-digit timer option to ReceiveSF.

- channels/sig_analog.c
It is customary to allow # to terminate digit collection immediately when there would normally be a timeout. However, currently, users are forced to wait for the timeout to expire when dialing numbers that are prefixes of other valid matches, and there is no way to end the timeout early. Customarily, # terminates the timeout, but at the moment, this is just rejected unless there happens to be a matching extension ending in #.
Allow # to terminate the timeout in cases where there is no dialplan match. This ensures that the dialplan is always respected, but if a valid extension has been dialed that happens to prefix other valid matches, # can be used to dial it immediately.
Resolves: #1510
> sig_analog: Allow '#' to end the inter-digit timeout when dialing.

- funcs/func_channel.c
Allow retrieving and setting the channel's ADSI capability from the dialplan.
Resolves: #1514
UserNote: CHANNEL(adsicpe) can now be read or written to change the channels' ADSI CPE capability setting.
> func_channel: Allow R/W of ADSI CPE capability setting.
